// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AacalUser
{
    public int Ikeyid { get; set; }

    public string Cname { get; set; }

    public bool Bflagrolltask { get; set; }

    public DateTime? Dlastroll { get; set; }

    public bool Bflagwarnuser { get; set; }

    public int Iwarninadv { get; set; }

    public bool Bflagaudiowarning { get; set; }

    public bool BFlagGroupWeekEnds { get; set; }

    public int ITimeDisplayIncrement { get; set; }

    public int Itimercheck { get; set; }

    public int IDefTaskTime { get; set; }

    public int Idefapptlen { get; set; }

    public int Idefpriority { get; set; }

    public int IAppointmentColor { get; set; }

    public int ITaskColor { get; set; }

    public int ICallColor { get; set; }

    public int IEventDayColor { get; set; }

    public int IUserScheduleColor { get; set; }

    public int ISoundId { get; set; }

    public string CWavfileName { get; set; }

    public int IKeyrollid { get; set; }

    public bool BFlagAppointmentsRequireName { get; set; }

    public bool BFlagShowCalls { get; set; }

    public bool BFlagShowTasks { get; set; }

    public bool BFlagShowAppointments { get; set; }

    public bool? BFlagShowWorkflow { get; set; }

    public bool? BFlagShowDepartment { get; set; }

    public bool? BFlagShowWorkflowTaskList { get; set; }

    public bool? BFlagShowDepartmentTaskList { get; set; }

    public int IDayOfWeekStart { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public Guid GUid { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public int IRecVersion { get; set; }

    public virtual ICollection<AacalEventNotification> AacalEventNotifications { get; set; } = new List<AacalEventNotification>();

    public virtual ICollection<AacalUserAccess> AacalUserAccesses { get; set; } = new List<AacalUserAccess>();
}