// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AacalEventDetail
{
    public int IKeyId { get; set; }

    public int IKeyEvent { get; set; }

    public int IKeyException { get; set; }

    public DateTime? DBegin { get; set; }

    public DateTime? DEnd { get; set; }

    public DateTime? DDue { get; set; }

    public DateTime? DJustDate { get; set; }

    public bool BFlagCompleted { get; set; }

    public bool BFlagRecurring { get; set; }

    public bool BFlagStartsAtZero { get; set; }

    public bool BFlagEndsAtMidnight { get; set; }

    public int IInstance { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual ICollection<AacalEventNotification> AacalEventNotifications { get; set; } = new List<AacalEventNotification>();

    public virtual AacalEvent IKeyEventNavigation { get; set; }
}