// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AacodeType
{
    public int IKeyId { get; set; }

    public string CCodeType { get; set; }

    public string CDescription { get; set; }

    public int IsortOrder { get; set; }

    public string CTable { get; set; }

    public bool BFlagEdit { get; set; }

    public bool BFlagCustom { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual ICollection<Aacode> Aacodes { get; set; } = new List<Aacode>();
}