// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AacomDue
{
    public int IKeyid { get; set; }

    public int Ikeypol { get; set; }

    public int Ikeynvst { get; set; }

    public int ICodecommdue { get; set; }

    public bool BflagEffeciveDate { get; set; }

    public DateTime? Dstartpayment { get; set; }

    public DateTime? Dendpayment { get; set; }

    public int Ifrequency { get; set; }

    public int Idayofweek { get; set; }

    public int Idayofmonth { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual Aapolicy IkeypolNavigation { get; set; }
}