// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class Aadebug
{
    public int IKeyId { get; set; }

    public DateTime? DLogDateTime { get; set; }

    public string CDesc { get; set; }

    public string CLongDesc { get; set; }

    public int? IPrimaryKey { get; set; }

    public string CTableName { get; set; }

    public int? IRelatedNameKey { get; set; }

    public string CLogType { get; set; }
}