// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AadownloadRegistrationAddress
{
    public int Ikeyid { get; set; }

    public int IKeyRegistration { get; set; }

    public int Icodeaddress { get; set; }

    public string CAddressCode { get; set; }

    public string CAddressDescription { get; set; }

    public string Cgreet { get; set; }

    public string Caddressee { get; set; }

    public string Ctitle { get; set; }

    public string CBusinessName { get; set; }

    public string Cstreet1 { get; set; }

    public string Cstreet2 { get; set; }

    public string Cstreet3 { get; set; }

    public string Ccity { get; set; }

    public string Cstate { get; set; }

    public string Czip { get; set; }

    public string CCounty { get; set; }

    public string Ccountry { get; set; }

    public int ICodeRecordCreationSource { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}