// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AadownloadRegistrationPhone
{
    public int IKeyId { get; set; }

    public int IKeyRegistration { get; set; }

    public int Icodephone { get; set; }

    public string CPhoneCode { get; set; }

    public string CPhoneDescription { get; set; }

    public string CFullPhone { get; set; }

    public int ICodeRecordCreationSource { get; set; }

    public string CContact { get; set; }

    public string CCountry { get; set; }

    public string CAreaCode { get; set; }

    public string CPhoneNum { get; set; }

    public string CPhoneExt { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}