// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AadownloadRegistration
{
    public int IKeyId { get; set; }

    public DateTime? DRecord { get; set; }

    public int IKeyAccount { get; set; }

    public int IKeyPolicy { get; set; }

    public string CNumber { get; set; }

    public string MDlRegistration { get; set; }

    public string CInvestorTaxId { get; set; }

    public string COwnerTaxId { get; set; }

    public DateTime? DInvestorDob { get; set; }

    public DateTime? DOwnerDob { get; set; }

    public string CAddressee { get; set; }

    public string CStreet1 { get; set; }

    public string CStreet2 { get; set; }

    public string CStreet3 { get; set; }

    public string CCity { get; set; }

    public string CState { get; set; }

    public string CZip { get; set; }

    public string CCountry { get; set; }

    public string CPhoneHome { get; set; }

    public string CPhoneBusiness { get; set; }

    public string CPhoneOther { get; set; }

    public string CEmail { get; set; }

    public int IKeyModule { get; set; }

    public int ICodeRecordCreationSource { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}