// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AafileHistoryLog
{
    public int IKeyId { get; set; }

    public int ICodeProcess { get; set; }

    public string CDescription { get; set; }

    public DateTime? DProcessed { get; set; }

    public string CDatabaseVersion { get; set; }

    public string CProgramVersion { get; set; }

    public string CPath { get; set; }

    public Guid? GUidReference { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}