// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AafileHistoryLogDetail
{
    public int IKeyId { get; set; }

    public int IKeyFileHistoryLog { get; set; }

    public string CContact { get; set; }

    public string CHolding { get; set; }

    public string CUser { get; set; }

    public DateTime? DFileDate { get; set; }

    public int ICodeDetailType { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}