// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class Aafile
{
    public int Ikeyid { get; set; }

    public int IkeyLink { get; set; }

    public string CDescription { get; set; }

    public string MFileName { get; set; }

    public string CFileLink { get; set; }

    public int Icodefilecat { get; set; }

    public int ICodeFileStatus { get; set; }

    public int Icodefilesource { get; set; }

    public DateTime? Dfiledate { get; set; }

    public string Cfileflag { get; set; }

    public int IFileSize { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual Aaname IkeyLinkNavigation { get; set; }
}