// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AaflexAccount
{
    public int IKeyId { get; set; }

    public decimal NFlexFld1 { get; set; }

    public decimal NFlexFld2 { get; set; }

    public decimal NFlexFld3 { get; set; }

    public decimal NFlexFld4 { get; set; }

    public decimal NFlexFld5 { get; set; }

    public decimal NFlexFld6 { get; set; }

    public int IFlexFld7 { get; set; }

    public int IFlexFld8 { get; set; }

    public string CFlexFld9 { get; set; }

    public string CFlexFld10 { get; set; }

    public string CFlesFld11 { get; set; }

    public string CFlexFld12 { get; set; }

    public DateTime? DFlexFld13 { get; set; }

    public DateTime? DFlexFld14 { get; set; }

    public DateTime? DFlexFld15 { get; set; }

    public DateTime? DFlexFld16 { get; set; }

    public string CFlexFld17 { get; set; }

    public string CFlexFld18 { get; set; }

    public string CFlexFld19 { get; set; }

    public string CFlexFld20 { get; set; }

    public DateTime? DFlexFld21 { get; set; }

    public DateTime? DFlexFld22 { get; set; }

    public string CFlexFld23 { get; set; }

    public string CFlexFld24 { get; set; }

    public string CFlexFld25 { get; set; }

    public string CFlexFld26 { get; set; }

    public string CFlexFld27 { get; set; }

    public string CFlexFld28 { get; set; }

    public string CFlexFld29 { get; set; }

    public string CFlexFld30 { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}