// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AaflexLabelWorkflow
{
    public int IKeyId { get; set; }

    public int IKeyWorkflowMaster { get; set; }

    public string Cflabel01 { get; set; }

    public string Cflabel02 { get; set; }

    public string Cflabel03 { get; set; }

    public string Cflabel04 { get; set; }

    public string Cflabel05 { get; set; }

    public string Cflabel06 { get; set; }

    public string Cflabel07 { get; set; }

    public string Cflabel08 { get; set; }

    public string Cflabel09 { get; set; }

    public string Cflabel10 { get; set; }

    public string Cflabel11 { get; set; }

    public string Cflabel12 { get; set; }

    public string Cflabel13 { get; set; }

    public string Cflabel14 { get; set; }

    public string Cflabel15 { get; set; }

    public string Cflabel16 { get; set; }

    public string Cflabel17 { get; set; }

    public string Cflabel18 { get; set; }

    public string Cflabel19 { get; set; }

    public string Cflabel20 { get; set; }

    public string Cflabel21 { get; set; }

    public string Cflabel22 { get; set; }

    public string Cflabel23 { get; set; }

    public string Cflabel24 { get; set; }

    public string Cflabel25 { get; set; }

    public string Cflabel26 { get; set; }

    public string Cflabel27 { get; set; }

    public string Cflabel28 { get; set; }

    public string Cflabel29 { get; set; }

    public string Cflabel30 { get; set; }

    public string CChoices9 { get; set; }

    public string CChoices10 { get; set; }

    public string CChoices11 { get; set; }

    public string CChoices12 { get; set; }

    public string CChoices17 { get; set; }

    public string CChoices18 { get; set; }

    public string CChoices19 { get; set; }

    public string CChoices20 { get; set; }

    public string CChoices23 { get; set; }

    public string CChoices24 { get; set; }

    public string CChoices25 { get; set; }

    public string CChoices26 { get; set; }

    public string CChoices27 { get; set; }

    public string CChoices28 { get; set; }

    public string CChoices29 { get; set; }

    public string CChoices30 { get; set; }

    public bool BFlagReadOnly1 { get; set; }

    public bool BFlagReadOnly2 { get; set; }

    public bool BFlagReadOnly3 { get; set; }

    public bool BFlagReadOnly4 { get; set; }

    public bool BFlagReadOnly5 { get; set; }

    public bool BFlagReadOnly6 { get; set; }

    public bool BFlagReadOnly7 { get; set; }

    public bool BFlagReadOnly8 { get; set; }

    public bool BFlagReadOnly9 { get; set; }

    public bool BFlagReadOnly10 { get; set; }

    public bool BFlagReadOnly11 { get; set; }

    public bool BFlagReadOnly12 { get; set; }

    public bool BFlagReadOnly13 { get; set; }

    public bool BFlagReadOnly14 { get; set; }

    public bool BFlagReadOnly15 { get; set; }

    public bool BFlagReadOnly16 { get; set; }

    public bool BFlagReadOnly17 { get; set; }

    public bool BFlagReadOnly18 { get; set; }

    public bool BFlagReadOnly19 { get; set; }

    public bool BFlagReadOnly20 { get; set; }

    public bool BFlagReadOnly21 { get; set; }

    public bool BFlagReadOnly22 { get; set; }

    public bool BFlagReadOnly23 { get; set; }

    public bool BFlagReadOnly24 { get; set; }

    public bool BFlagReadOnly25 { get; set; }

    public bool BFlagReadOnly26 { get; set; }

    public bool BFlagReadOnly27 { get; set; }

    public bool BFlagReadOnly28 { get; set; }

    public bool BFlagReadOnly29 { get; set; }

    public bool BFlagReadOnly30 { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}