// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AaformMaster
{
    public int IKeyId { get; set; }

    public int IKeyLink { get; set; }

    public int IPageId { get; set; }

    public string CFormCode { get; set; }

    public string CDescription { get; set; }

    public string CLine01 { get; set; }

    public string CLine02 { get; set; }

    public string CLine03 { get; set; }

    public string CLine04 { get; set; }

    public string CLine05 { get; set; }

    public string CLine06 { get; set; }

    public string CLine07 { get; set; }

    public string CLine08 { get; set; }

    public string CLine09 { get; set; }

    public string CLine10 { get; set; }

    public string CLine11 { get; set; }

    public string CLine12 { get; set; }

    public string CLine13 { get; set; }

    public string CLine14 { get; set; }

    public string CLine15 { get; set; }

    public string CLine16 { get; set; }

    public string CLine17 { get; set; }

    public string CLine18 { get; set; }

    public string CLine19 { get; set; }

    public DateTime? DPageDate { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}