// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AaformName
{
    public int Ikeyid { get; set; }

    public int Ikeylink { get; set; }

    public int IPageId { get; set; }

    public string Cformcode { get; set; }

    public string Cdescription { get; set; }

    public string Cline01 { get; set; }

    public string Cline02 { get; set; }

    public string Cline03 { get; set; }

    public string Cline04 { get; set; }

    public string Cline05 { get; set; }

    public string Cline06 { get; set; }

    public string Cline07 { get; set; }

    public string Cline08 { get; set; }

    public string Cline09 { get; set; }

    public string CLine10 { get; set; }

    public string CLine11 { get; set; }

    public string CLine12 { get; set; }

    public string CLine13 { get; set; }

    public string CLine14 { get; set; }

    public string CLine15 { get; set; }

    public string CLine16 { get; set; }

    public string CLine17 { get; set; }

    public string CLine18 { get; set; }

    public string CLine19 { get; set; }

    public DateTime? DPageDate { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid Guid { get; set; }

    public int IRecVersion { get; set; }

    public virtual Aaname IkeylinkNavigation { get; set; }
}