// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AagoogleAccount
{
    public int Ikeyid { get; set; }

    public int IKeyUser { get; set; }

    public string CGmailAddress { get; set; }

    public string CPasswordEncrypted { get; set; }

    public string COauth2KeyEncrypted { get; set; }

    public string COauth2KeyRefreshEncrypted { get; set; }

    public string CClientX509Uri { get; set; }

    public DateTime? TAalastEmailSynch { get; set; }

    public DateTime? TServiceLastEmailSynch { get; set; }

    public bool? BFlagEnableGoogleSynch { get; set; }

    public bool? BFlagServiceSynchEmail { get; set; }

    public bool? BFlagServiceSynchCalendar { get; set; }

    public bool? BFlagServiceSynchContacts { get; set; }

    public bool? BFlagServiceBirthdaysAnniversaries { get; set; }

    public bool? BFlagServiceSyncThisUserGlobal { get; set; }

    public string CServiceCategory { get; set; }

    public int IKeyServiceProducer { get; set; }

    public bool BFlagArchiveIncomingEmail { get; set; }

    public bool BFlagArchiveOutgoingEmail { get; set; }

    public int IArchiveCheckDays { get; set; }

    public int IArchiveDaysOption { get; set; }

    public int IMailboxSearchOption { get; set; }

    public bool? BFlagDoNotArchiveAttachments { get; set; }

    public bool BFlagDoNotArchiveEmailLabeledPrivate { get; set; }

    public bool BRealTimeEventsExport { get; set; }

    public string CCredentialObjectEncrypted { get; set; }

    public string CGoogleGroupsListLastSave { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}