// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AahouseHold
{
    public int IKeyId { get; set; }

    public int IKeyClient { get; set; }

    public int IKeyAddress { get; set; }

    public int IKeyPhone { get; set; }

    public int ICodeHouseHoldType { get; set; }

    public int ICodeNameType { get; set; }

    public bool BFlagForcePrimaryAddress { get; set; }

    public bool BFlagForcePrimaryPhone { get; set; }

    public string CDescription { get; set; }

    public decimal YIncome { get; set; }

    public string CRiskAlyzeRiskNumber { get; set; }

    public int IRiskAlyzeId { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual ICollection<AahouseHoldMember> AahouseHoldMembers { get; set; } = new List<AahouseHoldMember>();
}