// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AainsuranceRelation
{
    public int Ikeyid { get; set; }

    public int Ikeypol { get; set; }

    public int Ikeycov { get; set; }

    public int Ikeyclient { get; set; }

    public int Icodereltype { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}