// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class Aalicense
{
    public int IKeyId { get; set; }

    public int IKeyUser { get; set; }

    public string CName { get; set; }

    public string CStreet1 { get; set; }

    public string CStreet2 { get; set; }

    public string CCity { get; set; }

    public string CState { get; set; }

    public string CZip { get; set; }

    public string CCountry { get; set; }

    public string CPhone { get; set; }

    public string CPhone2 { get; set; }

    public string CEmail { get; set; }

    public string CContact { get; set; }

    public string CUrl { get; set; }

    public string CVersionType { get; set; }

    public int IStations { get; set; }

    public string CHashCode { get; set; }

    public bool BFlagTrialPeriod { get; set; }

    public string CConnectionString { get; set; }

    public Guid GUidSystemId { get; set; }

    public int ICodeReconcileFrequency { get; set; }

    public decimal NReconcileTolerance { get; set; }

    public bool? BFlagValidateTaxIdlookup { get; set; }

    public bool? BFlagSeperateOutlookTasks { get; set; }

    public DateTime? DLastReindex { get; set; }

    public DateTime? DLastBackup { get; set; }

    public DateTime? DNextBackupReminder { get; set; }

    public DateTime? DNextUpdateReminder { get; set; }

    public int ICodeCommissionsDirectPay { get; set; }

    public bool? BMessengerAllowReply { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual ICollection<AalicenseModule> AalicenseModules { get; set; } = new List<AalicenseModule>();

    public virtual Aauser IKeyUserNavigation { get; set; }
}