// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AamailingList
{
    public int Ikeyid { get; set; }

    public string CDescription { get; set; }

    public int ICodeNameType { get; set; }

    public int IKeyProducer { get; set; }

    public bool BFlagOrganization { get; set; }

    public string MMapXml { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}