// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AanameDeleted
{
    public int Ikeyid { get; set; }

    public string Cfirstname { get; set; }

    public string Cmiddle { get; set; }

    public string Clastname { get; set; }

    public string CPrimaryProducerName { get; set; }

    public string CPrimaryNameType { get; set; }

    public DateTime? Ddob { get; set; }

    public string CWhoChange { get; set; }

    public DateTime DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime DWhenAdded { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}