// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AanameAdvisorVault
{
    public int Ikeyid { get; set; }

    public int IKeyName { get; set; }

    public string CFirstName { get; set; }

    public string CLastName { get; set; }

    public string CEmail { get; set; }

    public string CAaproducerCName { get; set; }

    public string CAvclientUserName { get; set; }

    public string CAvadvisorUserName { get; set; }

    public string MComment { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}