// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AanameType
{
    public int Ikeyid { get; set; }

    public int Ikeyclient { get; set; }

    public int IKeyHouseHold { get; set; }

    public int Icodenametype { get; set; }

    public bool BFlagPrimary { get; set; }

    public int ISortOrder { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual Aaname IkeyclientNavigation { get; set; }
}