// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AanameFilter
{
    public int Ikeyid { get; set; }

    public int Ikeyname { get; set; }

    public int Ikeyuser { get; set; }
}