// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class Aanote
{
    public int Ikeyid { get; set; }

    public int ICodeTextFormat { get; set; }

    public bool Bflagarchived { get; set; }

    public bool BFlagPersonalContact { get; set; }

    public string MNotePage { get; set; }

    public int IKeyPrivateUser { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public DateTime? DRowCreated { get; set; }
}