// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AanvstAccountRelation
{
    public int IKeyId { get; set; }

    public int IKeyAcct { get; set; }

    public int IKeyClient { get; set; }

    public bool BFlagPrimary { get; set; }

    public int ICodeRelType { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    /// <summary>
    /// &quot; &quot;
    /// </summary>
    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}