// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AanvstValue
{
    public int Ikeyid { get; set; }

    public DateTime? DValdate { get; set; }

    public DateTime? DValuedRor { get; set; }

    public DateTime? DLastTransaction { get; set; }

    public DateTime? DProcessStart { get; set; }

    public decimal Ymktval { get; set; }

    public decimal Nunitval { get; set; }

    public decimal Nnumunits { get; set; }

    public decimal NLastProcessUnits { get; set; }

    public decimal YDistributionsPaidOut { get; set; }

    public decimal YDistributionsReinvested { get; set; }

    public decimal YCapGainLongPaidOut { get; set; }

    public decimal YCapGainShortPaidOut { get; set; }

    public decimal YInterestPaidOut { get; set; }

    public decimal YDividendPaidOut { get; set; }

    public decimal YCapGainLongReinvested { get; set; }

    public decimal YCapGainShortReinvested { get; set; }

    public decimal YInterestReinvested { get; set; }

    public decimal YDividendReinvested { get; set; }

    public decimal YAccountMoneyIn { get; set; }

    public decimal YAccountMoneyOut { get; set; }

    public decimal YAccountMoneyNet { get; set; }

    public decimal YMoneyIn { get; set; }

    public decimal YMoneyOut { get; set; }

    public decimal YClientMoneyIn { get; set; }

    public decimal YClientMoneyOut { get; set; }

    public decimal YClientNet { get; set; }

    public decimal YOutSideMoneyIn { get; set; }

    public decimal YOutSideMoneyOut { get; set; }

    public decimal YOutSideMoneyNet { get; set; }

    public decimal YNetTransfers { get; set; }

    public decimal YNetExpenses { get; set; }

    public decimal YNetFees { get; set; }

    public decimal YNetAdjustments { get; set; }

    public decimal YNetGift { get; set; }

    public decimal YCommissions { get; set; }

    public decimal YTransactionCost { get; set; }

    public decimal YUnrealGain { get; set; }

    public decimal YUnrealGain1Year { get; set; }

    public decimal YUnrealgainOver1year { get; set; }

    public decimal YRealGain { get; set; }

    public decimal YCostBasis { get; set; }

    public decimal? YRealGain1Year { get; set; }

    public decimal YRealGainOver1Year { get; set; }

    public DateTime? Drorbegin { get; set; }

    public decimal Nrortime { get; set; }

    public decimal Nrordollar { get; set; }

    public decimal NRorSimple { get; set; }

    public decimal YOnDeposit { get; set; }

    public DateTime? DLastInterestCalc { get; set; }

    public DateTime? DNextInterestCalc { get; set; }

    public decimal YInterestToDate { get; set; }

    public decimal YInterestAccrued { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual ICollection<Aanvst> Aanvsts { get; set; } = new List<Aanvst>();
}