// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AanvTransBlotter
{
    public int IKeyId { get; set; }

    public int IKeyApprovalName { get; set; }

    public DateTime? DOrderEntry { get; set; }

    public DateTime? DFill { get; set; }

    public DateTime? DApproval { get; set; }

    public int ICodeOrderType { get; set; }

    public int ICodeOrderDuration { get; set; }

    public int ICodeApprovalStatus { get; set; }

    public bool BFlagSolicitated { get; set; }

    public string MNotes { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid? GUid { get; set; }

    public int IRecVersion { get; set; }
}