// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AanvstProcessTransactionKey
{
    public int IKeyUser { get; set; }

    public int IKeyNvst { get; set; }

    public int IKeyTransaction { get; set; }

    public bool BFlagFreezeBasis { get; set; }

    public long Bflaginit { get; set; }
}