// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AanvstIndexPrice
{
    public int IKeyId { get; set; }

    public int IKeyIndex { get; set; }

    public int IKeyModule { get; set; }

    public DateTime? DPrice { get; set; }

    public decimal NClose { get; set; }

    public decimal NHigh { get; set; }

    public decimal NLow { get; set; }

    public decimal NMonthReturn { get; set; }

    public decimal NQtrReturn { get; set; }

    public decimal NYtdreturn { get; set; }

    public decimal N1YearReturn { get; set; }

    public decimal N3YearReturn { get; set; }

    public decimal N3YearReturnAnnualized { get; set; }

    public decimal N5YearReturn { get; set; }

    public decimal N5YearReturnAnnualized { get; set; }

    public decimal N10YearReturn { get; set; }

    public decimal N10YearReturnAnnualized { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int? IRecVersion { get; set; }
}