// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AanvstSymbol
{
    public int Ikeyid { get; set; }

    public int Ikeymgr { get; set; }

    public int IKeyModule { get; set; }

    public bool BFlagAddedByDownloadModule { get; set; }

    public int IKeyModuleCreated { get; set; }

    public int IKeyDlfaddProcess { get; set; }

    public int IKeyDlfbatchCreated { get; set; }

    public int IKeyUnderlyingSecurity { get; set; }

    public int IKeyDlffileCreated { get; set; }

    public string CCodeId { get; set; }

    public string Cdescription { get; set; }

    public string Ccusip { get; set; }

    public string Ccusipext { get; set; }

    public string Coldcusip { get; set; }

    public string Coldext { get; set; }

    public string Calternateid { get; set; }

    public string COldAlternate { get; set; }

    public string CShareClass { get; set; }

    public string CCarrierPriceId { get; set; }

    public string CUnderlyingFund { get; set; }

    public string CPriceDownloadId { get; set; }

    public DateTime? DLastPriceDownload { get; set; }

    public int Icodecompany { get; set; }

    public int Icodenvsttype { get; set; }

    public int Icodeobjective { get; set; }

    public int Icodecategory { get; set; }

    public int Icodesector { get; set; }

    public int ICodeAssetClass { get; set; }

    public int ICodeCountry { get; set; }

    public int ICodeExchange { get; set; }

    public int ICodeSecurityCurrency { get; set; }

    public int ICodeRisk { get; set; }

    public int ICodeLiquidity { get; set; }

    public int ICodeUpdate { get; set; }

    public int ICodeBasisOnReinvestment { get; set; }

    public string CAutoPriceCountry { get; set; }

    public string CAutoPriceExchange { get; set; }

    public decimal Nbeta { get; set; }

    public decimal NAlpha { get; set; }

    public decimal Nyield { get; set; }

    public decimal NStandardDeviation { get; set; }

    public decimal Nfactor { get; set; }

    public decimal Nshrfactor { get; set; }

    public bool BFlagUserOverrideFactors { get; set; }

    public bool BFlagPool { get; set; }

    public decimal Nnormalload { get; set; }

    public decimal Nyieldval { get; set; }

    public int ICodeReconcileFrequency { get; set; }

    public decimal NReconcileTolerance { get; set; }

    public bool BFlagFixedIncomeObligation { get; set; }

    public bool BFlagIntBear { get; set; }

    public bool BFlagAccrueInt { get; set; }

    public bool BFlagInterestInDlpositions { get; set; }

    public decimal NAnnualInterestRate { get; set; }

    public DateTime? DCallable { get; set; }

    public decimal YCallPrice { get; set; }

    public DateTime? DMature { get; set; }

    public bool BFlagTrailerCommission { get; set; }

    public decimal NTrailerCommissionPct { get; set; }

    public short ITrailerCommTimesYear { get; set; }

    public int ITrailerBeginsNmonthsAfterAcquired { get; set; }

    public decimal NTrailerBasisPoints { get; set; }

    public DateTime? DTrailerBegin { get; set; }

    public DateTime? DTrailerPaidThru { get; set; }

    public bool Bflagfixedval { get; set; }

    public bool Bflagincreasecb { get; set; }

    public bool BFlagFixedValueTaxLot { get; set; }

    public decimal N10yearreturn { get; set; }

    public decimal N5yearreturn { get; set; }

    public decimal N3yearreturn { get; set; }

    public decimal N1yearreturn { get; set; }

    public bool BFlagOption { get; set; }

    public DateTime? DOptionExpiration { get; set; }

    public decimal YStrikePrice { get; set; }

    public DateTime? DDlRegistration { get; set; }

    public DateTime? DDlPosition { get; set; }

    public DateTime? DDlPrice { get; set; }

    public DateTime? DDlSecurity { get; set; }

    public bool BFlagOverridePositionEod { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}