// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AanvTran
{
    public int Ikeyid { get; set; }

    public int IKeyNvst { get; set; }

    public int IkeyLinkedTrans { get; set; }

    public int IkeyTranType { get; set; }

    public int IKeyCancel { get; set; }

    public int IKeyCancelBy { get; set; }

    public int IKeyModule { get; set; }

    public int IKeyValuationCalc { get; set; }

    public int IKeyValuationFlow { get; set; }

    public int IKeySplit { get; set; }

    public int IKeyBlotter { get; set; }

    public int IKeyDlffileCreated { get; set; }

    public int ICalcOrder { get; set; }

    public DateTime? DTrandate { get; set; }

    public DateTime? DSettle { get; set; }

    public DateTime? DTransmittal { get; set; }

    public DateTime? DCancelled { get; set; }

    public bool BFlagCancelled { get; set; }

    public bool BFlagFreezeBasis { get; set; }

    public bool BFlagNoTrigger { get; set; }

    public bool Bflagreconcile { get; set; }

    public bool Bflaginit { get; set; }

    public bool BFlagBlotter { get; set; }

    public string CDltranCodePrimary { get; set; }

    public string CDltranCodeSecondary { get; set; }

    public string Cref { get; set; }

    public string Cref2 { get; set; }

    public string MComment { get; set; }

    public decimal Nshares { get; set; }

    public decimal NSharesEligible { get; set; }

    public decimal NShareBasis { get; set; }

    public decimal Nshareprice { get; set; }

    public decimal YPrincipal { get; set; }

    public decimal YLoadIncluded { get; set; }

    public decimal YCommIncluded { get; set; }

    public decimal YCommExcluded { get; set; }

    public decimal YFeesExcluded { get; set; }

    public decimal YMiscExcluded { get; set; }

    public decimal YAccruedIntExcluded { get; set; }

    public decimal YClientTotal { get; set; }

    public decimal YBegAccruedInt { get; set; }

    public decimal YBasisIn { get; set; }

    public decimal YBasisOut { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual Aanvst IKeyNvstNavigation { get; set; }

    public virtual AanvTransType IkeyTranTypeNavigation { get; set; }
}