// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AanvstNavTemp
{
    public int IKeyId { get; set; }

    public int IKeySymbol { get; set; }

    public int IKeyIndex { get; set; }

    public int IKeyModule { get; set; }

    public int IKeyDlffileCreated { get; set; }

    public DateTime? DNav { get; set; }

    public decimal NNav { get; set; }

    public decimal NHigh { get; set; }

    public decimal NLow { get; set; }

    public int IVolume { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public int IRecVersion { get; set; }

    public string CSerialId { get; set; }

    public Guid GGuid { get; set; }
}