// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AaoutlookEntryCalendar
{
    public int IKeyId { get; set; }

    public int IKeyStore { get; set; }

    public int IKeyAalink { get; set; }

    public string COutlookItemEntryId { get; set; }

    public DateTime? DLastSynch { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual AaoutlookStore IKey { get; set; }

    public virtual AacalEvent IKeyAalinkNavigation { get; set; }
}