// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class Aaperspective
{
    public int IKeyId { get; set; }

    public string CName { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual ICollection<AaperspectiveCode> AaperspectiveCodes { get; set; } = new List<AaperspectiveCode>();

    public virtual ICollection<AaperspectiveTransCode> AaperspectiveTransCodes { get; set; } = new List<AaperspectiveTransCode>();
}