// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AapolicyModalPremiumCoverage
{
    public int Ikeyid { get; set; }

    public int IkeyLink { get; set; }

    public int IYear { get; set; }

    public decimal YBase { get; set; }

    public decimal YExcess { get; set; }

    public decimal YExcess2 { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual AapolicyCoverage IkeyLinkNavigation { get; set; }
}