// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AapolicySeries
{
    public int Ikeyid { get; set; }

    public int IKeySurrenderChargeTable { get; set; }

    public string CCodeId { get; set; }

    public int ICodeCovType { get; set; }

    public string CXmlKey { get; set; }

    public int Icodecompany { get; set; }

    public int ICodeFundingOption { get; set; }

    public int IKeyModule { get; set; }

    public string CDescription { get; set; }

    public string Cproductid { get; set; }

    public string Cproductidold { get; set; }

    public string Ccarrierid { get; set; }

    public bool Bflagdiv { get; set; }

    public bool Bflagportable { get; set; }

    public bool Bflagconvertable { get; set; }

    public int ICodeProductClass { get; set; }

    public decimal Nguarintrate { get; set; }

    public decimal Ncurrloanintrate { get; set; }

    public string Cagecalculation { get; set; }

    public int Ipaytoage { get; set; }

    public int Ipaytoyear { get; set; }

    public string CBenefitDescription1 { get; set; }

    public string CBenefitDescription2 { get; set; }

    public string CV2series { get; set; }

    public int IKeyDefaultCommissionRateTableSet { get; set; }

    public bool? BFlagWarnWhenCalculatingCommissions { get; set; }

    public int ICodeAnnuitySurrenderPeriod { get; set; }

    public decimal NMortalityExpenseRate { get; set; }

    public bool BFlagCommRenewalOnCalendarYear { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual ICollection<AapolicyBenefitSeries> AapolicyBenefitSeries { get; set; } = new List<AapolicyBenefitSeries>();
}