// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AapolicyCommTransactionDueRiderLink
{
    public int IKeyId { get; set; }

    public int IKeyDue { get; set; }

    public int IKeyRider { get; set; }

    public int IKeyRateTableSet { get; set; }

    public int IRiderYear { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}