// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AapolicySur
{
    public int Ikeyid { get; set; }

    public string CSurrCode { get; set; }

    public string CDescription { get; set; }

    public int Iperiodfixed01 { get; set; }

    public int Iperiodfixed02 { get; set; }

    public int Iperiodfixed03 { get; set; }

    public int Iperiodfixed04 { get; set; }

    public int Iperiodfixed05 { get; set; }

    public int Iperiodfixed06 { get; set; }

    public int Iperiodfixed07 { get; set; }

    public int Iperiodfixed08 { get; set; }

    public int Iperiodfixed09 { get; set; }

    public int Iperiodfixed10 { get; set; }

    public int Iperiodfixed11 { get; set; }

    public int Iperiodfixed12 { get; set; }

    public int Iperiodfixed13 { get; set; }

    public int Iperiodfixed14 { get; set; }

    public int Iperiodfixed15 { get; set; }

    public decimal Nperiodpct01 { get; set; }

    public decimal Nperiodpct02 { get; set; }

    public decimal Nperiodpct03 { get; set; }

    public decimal Nperiodpct04 { get; set; }

    public decimal Nperiodpct05 { get; set; }

    public decimal Nperiodpct06 { get; set; }

    public decimal Nperiodpct07 { get; set; }

    public decimal Nperiodpct08 { get; set; }

    public decimal Nperiodpct09 { get; set; }

    public decimal Nperiodpct10 { get; set; }

    public decimal Nperiodpct11 { get; set; }

    public decimal Nperiodpct12 { get; set; }

    public decimal Nperiodpct13 { get; set; }

    public decimal Nperiodpct14 { get; set; }

    public decimal Nperiodpct15 { get; set; }

    public int Iperiod2start { get; set; }

    public int Iperiod3start { get; set; }

    public int Iperiod4start { get; set; }

    public int Iperiod5start { get; set; }

    public int Iperiod6start { get; set; }

    public int Iperiod7start { get; set; }

    public int Iperiod8start { get; set; }

    public int Iperiod9start { get; set; }

    public int Iperiod10start { get; set; }

    public int Iperiod11start { get; set; }

    public int Iperiod12start { get; set; }

    public int Iperiod13start { get; set; }

    public int Iperiod14start { get; set; }

    public int Iperiod15start { get; set; }

    public int Izeroedout { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}