// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AapolicyCoverage
{
    public int IKeyId { get; set; }

    public int IkeyPol { get; set; }

    public int IKeyGroupMaster { get; set; }

    public bool BFlagGroupMaster { get; set; }

    public int IKeyCommissionRateTable { get; set; }

    public int IKeyFlex { get; set; }

    public int IKeySeries { get; set; }

    public int IKeySeriesDownloaded { get; set; }

    public int IKeyPrimaryInsured { get; set; }

    public int IKeyPrimaryBeneficiary { get; set; }

    public int IKeyUnderWriter { get; set; }

    public int IKeyFundingAccount { get; set; }

    public string CxmKey { get; set; }

    public int IIndicatorCode { get; set; }

    public int ICodeRenewalProvision { get; set; }

    public int ICodeStatus { get; set; }

    public int ICodeBenefitMode { get; set; }

    public int ICodeBenefitPer { get; set; }

    public int ICodeDivOpt { get; set; }

    public int ICodeDeathBenefitOption { get; set; }

    public int ICodeApprovalBasis { get; set; }

    public int ICodeAccBenefitPer { get; set; }

    public int ICodeSickBenefitPer { get; set; }

    public int ICodeAccElimPer { get; set; }

    public int ICodeSickElimPer { get; set; }

    public int ICodeDeductibleMax { get; set; }

    public int ICodeDeductiblePer { get; set; }

    public int ICodeInflationProtection { get; set; }

    public int ICodefundingOption { get; set; }

    public int ICodeAnnuitySurrenderPeriod { get; set; }

    public string CFundingAccountNumber { get; set; }

    public bool BFlagCalculateSurrenderValue { get; set; }

    public bool BFlagCalculateCommissions { get; set; }

    public bool BFlagAddToBen { get; set; }

    public decimal YBenefitAmtCov { get; set; }

    public decimal YCashWithApp { get; set; }

    public decimal YBenefitAmtAccident { get; set; }

    public decimal YBenefitAmtSickness { get; set; }

    public decimal YDeductible { get; set; }

    public decimal YDeductibleFamily { get; set; }

    public decimal YAnnBasePrem { get; set; }

    public decimal YAnnExcess1Prem { get; set; }

    public decimal YAnnExcess2Prem { get; set; }

    public decimal YLastPremPaymentAmt { get; set; }

    public decimal YPremiumToDate { get; set; }

    public decimal YCashval { get; set; }

    public decimal YOtherValue { get; set; }

    public decimal YSurrenderCharge { get; set; }

    public decimal YloanAmt { get; set; }

    public decimal YNetCashValue { get; set; }

    public decimal NAnnualBaseCommission { get; set; }

    public decimal NAnnualExcess1Commission { get; set; }

    public decimal NAnnualExcess2Commission { get; set; }

    public decimal YTotalAnnualPrem { get; set; }

    public decimal YTotalModalPrem { get; set; }

    public decimal YTotalBenefitAmt { get; set; }

    public decimal YNetBenefit { get; set; }

    public decimal YTotalAnnualCommission { get; set; }

    public decimal YTotalRiderAnnualPrem { get; set; }

    public decimal YTotalRiderModalPrem { get; set; }

    public decimal YTotalRiderCashValue { get; set; }

    public decimal YTotalRiderLoans { get; set; }

    public decimal YTrackedAccountMarketValue { get; set; }

    public int IParticipants { get; set; }

    public DateTime? DInitial { get; set; }

    public DateTime? DSubmit { get; set; }

    public DateTime? DEffective { get; set; }

    public int? IEffective { get; set; }

    public DateTime? DRenewal { get; set; }

    public DateTime? DExpiration { get; set; }

    public DateTime? DTermination { get; set; }

    public DateTime? DConversion { get; set; }

    public DateTime? DFinalPayment { get; set; }

    public DateTime? DTrackedAccountMarketValueAsOf { get; set; }

    public int ICodeBeneficiaryType { get; set; }

    public string MBeneficiary { get; set; }

    public DateTime? DCommPaidThru { get; set; }

    public DateTime? DcommBegin { get; set; }

    public DateTime? DCommEnd { get; set; }

    public DateTime? DCommPaidThruProducer1 { get; set; }

    public DateTime? DCommPaidThruProducer2 { get; set; }

    public DateTime? DCommPaidThruProducer3 { get; set; }

    public DateTime? DCommPaidThruProducer4 { get; set; }

    public DateTime? DCommPaidThruManager1 { get; set; }

    public DateTime? DCommPaidThruManager2 { get; set; }

    public DateTime? DCommPaidThruManager3 { get; set; }

    public DateTime? DCommPaidThruManager4 { get; set; }

    public int ICodeRecordCreationSource { get; set; }

    public DateTime? DDlRegistration { get; set; }

    public int IKeyPosition { get; set; }

    public bool BFlagUsePosition { get; set; }

    public string COccupationClass { get; set; }

    public decimal NInterestRate { get; set; }

    public decimal NMortalityExpenseRate { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public DateTime? DCommRenewalStart { get; set; }

    public virtual ICollection<AaformCoverage> AaformCoverages { get; set; } = new List<AaformCoverage>();

    public virtual ICollection<AapolicyBenefitCoverage> AapolicyBenefitCoverages { get; set; } = new List<AapolicyBenefitCoverage>();

    public virtual ICollection<AapolicyCoverageRelation> AapolicyCoverageRelations { get; set; } = new List<AapolicyCoverageRelation>();

    public virtual ICollection<AapolicyModalPremiumCoverage> AapolicyModalPremiumCoverages { get; set; } = new List<AapolicyModalPremiumCoverage>();

    public virtual ICollection<AapolicyNewBiz> AapolicyNewBizs { get; set; } = new List<AapolicyNewBiz>();

    public virtual ICollection<AapolicyRider> AapolicyRiders { get; set; } = new List<AapolicyRider>();
}