// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AapolicyCommAdjustment
{
    public int IKeyId { get; set; }

    public int IKeyTransaction { get; set; }

    public int IKeyPayee { get; set; }

    public int IKeyPayor { get; set; }

    public int IKeyAgency { get; set; }

    public int ICodeAdjustmentType { get; set; }

    public int ICodePayorType { get; set; }

    public bool BFlagDebitPayor { get; set; }

    public int ICodePayeeType { get; set; }

    public bool BFlagCreditPayee { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}