// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AapolicyCommTableSet
{
    public int IKeyId { get; set; }

    public string CDescription { get; set; }

    public int ITrailersStartPolicyYear { get; set; }

    public int ITrailersStartMonth { get; set; }

    public int ICodeTrailerPaymentMode { get; set; }

    public int ICodePostingOptionOverride1 { get; set; }

    public int ICodePostingOptionOverride2 { get; set; }

    public int ICodePostingOptionExcess1 { get; set; }

    public int ICodePostingOptionExcess2 { get; set; }

    public int ICodePostingOptionPerParticipant { get; set; }

    public int ICodePostingOptionTrailer { get; set; }

    public int ICodePostingOptionRider { get; set; }

    public int ICodePostingOptionFixedAmount { get; set; }

    public bool BFlagNonCommFirstYearOnly { get; set; }

    public string MComment { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}