// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AaprocessValue
{
    public int IKeyId { get; set; }

    public DateTime? DStartRange { get; set; }

    public DateTime? DEndRange { get; set; }

    public bool BFlagProcessAll { get; set; }

    public bool BFlagCalculateBasis { get; set; }

    public bool BFlagCalculateRor { get; set; }

    public bool BFlagRebuildTaxLot { get; set; }

    public bool BFlagRebuildValuationTables { get; set; }

    public bool BFlagValidatePeriodicValuations { get; set; }

    public bool BFlagForceCalculation { get; set; }

    public string CPeriod { get; set; }

    public bool? BFlagSumm { get; set; }

    public bool BFlagUpdateAccount { get; set; }

    public string CProcessHeaderMessage { get; set; }

    public string CProcessResult { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public Guid GUid { get; set; }
}