// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AaprocessLogDetail
{
    public int IKeyId { get; set; }

    public int IKeyProcessLog { get; set; }

    public string CDescription1 { get; set; }

    public string CDescription2 { get; set; }

    public string CDescription3 { get; set; }

    public DateTime? DFileDate { get; set; }

    public int ICodeDetailType { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}