// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AaqueryCondition
{
    public int Ikeyid { get; set; }

    public int IBatch { get; set; }

    public int IReportKeyTable { get; set; }

    public string CUniqueConditionName { get; set; }

    public string CLabel { get; set; }

    public string CBaseClass { get; set; }

    public int IKeyQueryTable { get; set; }

    public string CQueryTableAlias { get; set; }

    public string CQueryColumn { get; set; }

    public string CExistsTableAlias { get; set; }

    public string CExistsColumn { get; set; }

    public int IColumnSqlType { get; set; }

    public string CTextFormat { get; set; }

    public int ISortOrder { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}