// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AareportPreference
{
    public int IKeyId { get; set; }

    public int IKeyReport { get; set; }

    public bool BFlagWebDisabled { get; set; }

    public bool BFlagDesktopDisabled { get; set; }

    public int ITimesRun { get; set; }

    public DateTime? DLastRunDate { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}