// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AareportCustomTitle
{
    public int IKeyId { get; set; }

    public int IKeyUser { get; set; }

    public int IKeyReport { get; set; }

    public string CCustomTitle1 { get; set; }

    public string CCustomTitle2 { get; set; }

    public string CCustomTitle3 { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}