// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AareportFootNote
{
    public int IKeyId { get; set; }

    public string CDescription { get; set; }

    public string MFootNote1 { get; set; }

    public string MFootNote2 { get; set; }

    public string MFootNote3 { get; set; }

    public string MFootNote0 { get; set; }

    public int IFootnoteFontSize1 { get; set; }

    public int IFootnoteFontSize2 { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual ICollection<Aareport> Aareports { get; set; } = new List<Aareport>();
}