// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AareportField
{
    public int IKeyId { get; set; }

    public int IKeyProgram { get; set; }

    public bool BFlagGroupable { get; set; }

    public string CName { get; set; }

    public string CDataField { get; set; }

    public int ICodeFieldType { get; set; }

    public int IWidth { get; set; }

    public int ISortOrder { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual AareportProgram IKeyProgramNavigation { get; set; }
}