// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class Aasystem
{
    public int Ikeyid { get; set; }

    public string CDataBaseVersion { get; set; }

    public string CBuildBranch { get; set; }

    public bool? BFlagRecreateViews { get; set; }

    public bool? BFlagValidateCodes { get; set; }

    public bool? BFlagValidateEncryption { get; set; }

    public bool? BFlagCheckPages { get; set; }

    public bool BFlagUsePages { get; set; }

    public bool? BFlagEnableLinksInNotes { get; set; }

    public bool BFlagEnableLinksInArchivedEmailNotes { get; set; }

    public bool BFlagPromptToCreateAutoLoginFile { get; set; }

    public bool BFlagEnableCustomLinks { get; set; }

    public bool? BFlagShowAdvisoryWorldMenuOption { get; set; }

    public bool? BFlagShowDstvisionMenuOption { get; set; }

    public bool? BFlagShowAlbridgeApplinkMenuOption { get; set; }

    public bool? BFlagEnableMessenger { get; set; }

    public bool? BFlagShowNotification { get; set; }

    public bool BFlagLogCalendarEventNotifications { get; set; }

    public bool BFlagLogMessageNotification { get; set; }

    public DateTime? DLastWorkflowUpdate { get; set; }

    public DateTime? DLastNoteIndexBuild { get; set; }

    public DateTime? DLastReindex { get; set; }

    public bool BFlagTradeDateCalculations { get; set; }

    public bool? BFlagCustomNavigationMenuVisible { get; set; }

    public string CCustomNavigationMenuUrl { get; set; }

    public bool BFlagPreventUsersFromChoosingSynchWithOutlook { get; set; }

    public bool BFlagPreventUsersFromChoosingSynchWithExchange { get; set; }

    public bool BFlagShowExchangeServiceUserPreferences { get; set; }

    public bool BFlagRestrictNewNametypesImportedFromOutlookOrExchange { get; set; }

    public string CExchangeServiceAccountLoginId { get; set; }

    public string CExchangeServiceAccountPassword { get; set; }

    public string CExchangeServiceAccountDomain { get; set; }

    public string CLocalStationUpdatePath { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}