// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AatempDatum
{
    public int IKeyId { get; set; }

    public string CString1 { get; set; }

    public string CString2 { get; set; }

    public string MText1 { get; set; }

    public string MText2 { get; set; }

    public DateTime? DDateTime1 { get; set; }

    public DateTime? DDateTime2 { get; set; }

    public bool BFlag1 { get; set; }

    public bool BFlag2 { get; set; }

    public decimal YMoney1 { get; set; }

    public decimal YMoney2 { get; set; }

    public int IInt1 { get; set; }

    public int IInt2 { get; set; }

    public decimal NRortime { get; set; }

    public decimal NRordollar { get; set; }

    public decimal NRorsimple { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}