// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AatempKeys1
{
    public long IKeyPrimary { get; set; }

    public int IKeyUser { get; set; }

    public int IKeyId { get; set; }
}