// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AauserModule
{
    public int IKeyId { get; set; }

    public int IKeyUser { get; set; }

    public int IKeyModule { get; set; }

    public string CAccess { get; set; }

    public string Cwhochange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CwhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual Aamodule IKeyModuleNavigation { get; set; }

    public virtual Aauser IKeyUserNavigation { get; set; }
}