// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AauserTaskType
{
    public int IKeyId { get; set; }

    public int IKeyGroup { get; set; }

    public int ICodeFunction { get; set; }

    public int ISortOrder { get; set; }

    public string CName { get; set; }

    public string MDescription { get; set; }

    public bool BFlagInsurance { get; set; }

    public bool BFlagInvestments { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual ICollection<AauserRoleTask> AauserRoleTasks { get; set; } = new List<AauserRoleTask>();

    public virtual ICollection<AauserTaskOverRide> AauserTaskOverRides { get; set; } = new List<AauserTaskOverRide>();

    public virtual AauserTaskTypeGroup IKeyGroupNavigation { get; set; }
}