// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AauserView
{
    public int Ikeyid { get; set; }

    public int IKeyVendor { get; set; }

    public int IKeyTop { get; set; }

    public string CViewLabel { get; set; }

    public string CViewName { get; set; }

    public bool BFlagAllProducer { get; set; }

    public bool BflagSuper { get; set; }

    public bool BFlagAllOffice { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual ICollection<AauserViewAccess> AauserViewAccesses { get; set; } = new List<AauserViewAccess>();

    public virtual ICollection<AauserViewOffice> AauserViewOffices { get; set; } = new List<AauserViewOffice>();

    public virtual ICollection<AauserViewPdcr> AauserViewPdcrs { get; set; } = new List<AauserViewPdcr>();
}