// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AauserDashboardWidget
{
    public int IKeyId { get; set; }

    public int IKeyUser { get; set; }

    public int IKeyWidget { get; set; }

    public int IColumn { get; set; }

    public int IRow { get; set; }

    public bool BFlagStretchable { get; set; }

    public string MConfig { get; set; }

    public string MConfigJson { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public Guid? GUid { get; set; }

    public int IRecVersion { get; set; }
}