// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AauserMessage
{
    public int Ikeyid { get; set; }

    public int Ikeysource { get; set; }

    public int Ikeytarget { get; set; }

    public int? Ikeyclient { get; set; }

    public int? Ikeytopic { get; set; }

    public bool BflagNotified { get; set; }

    public bool BFlagArchived { get; set; }

    public bool BFlagSenderDeleted { get; set; }

    public bool BFlagReceiverDeleted { get; set; }

    public DateTime? DReceived { get; set; }

    public DateTime? Dsent { get; set; }

    public string Mtext { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual Aaname IkeyclientNavigation { get; set; }

    public virtual Aauser IkeysourceNavigation { get; set; }

    public virtual Aauser IkeytargetNavigation { get; set; }
}