// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AauserTaskTypeSplit
{
    public int IKeyOldTask { get; set; }

    public int IKeyNewTask { get; set; }
}