// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AauserViewAccess
{
    public int IKeyId { get; set; }

    public int IKeyUser { get; set; }

    public int IKeyView { get; set; }

    public bool BFlagPrimary { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual Aauser IKeyUserNavigation { get; set; }

    public virtual AauserView IKeyViewNavigation { get; set; }
}