// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class Aauser
{
    public int IKeyId { get; set; }

    public int IKeyRole { get; set; }

    public int IKeyDefaultView { get; set; }

    public int IKeyCurrentView { get; set; }

    public int IKeyCalendar { get; set; }

    public int IKeyName { get; set; }

    public int IMaxRecentNames { get; set; }

    public string CRecordType { get; set; }

    public string CUserInitials { get; set; }

    public string CName { get; set; }

    public string CUserId { get; set; }

    public string CPassword { get; set; }

    public string CEmailAddress { get; set; }

    public string CRecordStamp { get; set; }

    public int IFailedLogin { get; set; }

    public string XPrevPasswords { get; set; }

    public DateTime? DLastLogin { get; set; }

    public DateTime? DLastLoginServerTime { get; set; }

    public DateTime? DLastPasswordChange { get; set; }

    public bool BFlagForcePasswordChange { get; set; }

    public bool BFlagDisable { get; set; }

    public bool BFlagDeactivate { get; set; }

    public bool BFlagNeedsEncryption { get; set; }

    public bool BFlagLoggedIn { get; set; }

    public bool BFlagNameFiltered { get; set; }

    public bool? BFlagMobileAccess { get; set; }

    public bool BFlagLimitedMobileAccess { get; set; }

    public bool BFlagPreventPasswordChange { get; set; }

    public string CStationName { get; set; }

    public int ISyncOption { get; set; }

    public bool BFlagOverrideAttachmentArchivePath { get; set; }

    public string COutlookAttachmentArchiveUserLocation { get; set; }

    public int IKeyLastBroadcastMessageReceived { get; set; }

    public Guid? GUidSsotoken { get; set; }

    public DateTime? TSsotokenExpiration { get; set; }

    public string CBurstReportingDefaultPath { get; set; }

    public string CDiagramLayoutLinksFromSource { get; set; }

    public bool BFlagPartialAlphabetLookup { get; set; }

    public int ICodeDefaultAddressLocation { get; set; }

    public int ICodeDefaultPhoneLocation { get; set; }

    public int IKeyDefaultProducer { get; set; }

    public int IKeyDefaultAgency { get; set; }

    public bool BFlagShowLiquidatedInvestments { get; set; }

    public bool BFlagShowIndividualInvestments { get; set; }

    public bool BFlagShowTerminatedPolicies { get; set; }

    public int ICodeViewClientPhoneDisplay1 { get; set; }

    public int ICodeViewClientPhoneDisplay2 { get; set; }

    public int IFormAutomationOption { get; set; }

    public string CLaserAppAnywhereUserId { get; set; }

    public string CLaserAppAnywherePasswordEncrypted { get; set; }

    public int IShowAdvisoryAccountsOption { get; set; }

    public int IDropDownCodeListDisplayOption { get; set; }

    public string CReadyDocServiceUrl { get; set; }

    public string CReadyDocApiurl { get; set; }

    public string CReadyDocClientId { get; set; }

    public string CReadyDocUserName { get; set; }

    public string CReadyDocPasswordEncrypted { get; set; }

    public string CRiskAlyzeToken { get; set; }

    public DateTime? DRiskAlyzeTokenExpires { get; set; }

    public string CRiskAlyzeRefreshToken { get; set; }

    public string CRiskAlyzeAccountId { get; set; }

    public string CRiskAlyzeAccountPw { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual ICollection<AacalUserAccess> AacalUserAccesses { get; set; } = new List<AacalUserAccess>();

    public virtual ICollection<Aalicense> Aalicenses { get; set; } = new List<Aalicense>();

    public virtual ICollection<AareportFavorite> AareportFavorites { get; set; } = new List<AareportFavorite>();

    public virtual ICollection<AauserMemo> AauserMemos { get; set; } = new List<AauserMemo>();

    public virtual ICollection<AauserMessage> AauserMessageIkeysourceNavigations { get; set; } = new List<AauserMessage>();

    public virtual ICollection<AauserMessage> AauserMessageIkeytargetNavigations { get; set; } = new List<AauserMessage>();

    public virtual ICollection<AauserModule> AauserModules { get; set; } = new List<AauserModule>();

    public virtual ICollection<AauserTaskOverRide> AauserTaskOverRides { get; set; } = new List<AauserTaskOverRide>();

    public virtual ICollection<AauserViewAccess> AauserViewAccesses { get; set; } = new List<AauserViewAccess>();

    public virtual AauserRoleType IKeyRoleNavigation { get; set; }
}