// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AauserMessageNotificationLog
{
    public int IKeyId { get; set; }

    public int IKeyMessage { get; set; }

    public int IKeyUser { get; set; }

    public DateTime? TMessage { get; set; }

    public DateTime? TNotified { get; set; }

    public DateTime? TAcknowledged { get; set; }

    public int INotificationType { get; set; }
}