// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class Aaweb
{
    public int IKeyId { get; set; }

    public int IKeyClient { get; set; }

    public bool BFlagPrimary { get; set; }

    public string CContact { get; set; }

    public string CBusinessName { get; set; }

    public string CAddress { get; set; }

    public string MComment { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }

    public virtual Aaname IKeyClientNavigation { get; set; }
}