// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AaworkFlowEventMaster
{
    public int Ikeyid { get; set; }

    public int IKeyWorkFlowMaster { get; set; }

    public int IKeyDefaultUser { get; set; }

    public int IKeyDefaultUserGroup { get; set; }

    public int ICodeWorkFlowEventType { get; set; }

    public int ICodePhase { get; set; }

    public int ISequence { get; set; }

    public string CDescription { get; set; }

    public int IDuration { get; set; }

    public int IWaitDaysAfterCompleted { get; set; }

    public bool BFlagRevenueStep { get; set; }

    public bool? BFlagDependency { get; set; }

    public bool BFlagAllowSkip { get; set; }

    public bool BFlagAssignToProducer { get; set; }

    public bool BFlagAssignToCurrentUser { get; set; }

    public string MNote { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}