// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class AaworkFlow
{
    public int IKeyId { get; set; }

    public int IKeyWorkFlowMaster { get; set; }

    public int IKeyName { get; set; }

    public int IKeyTopic { get; set; }

    public int IKeyAccount { get; set; }

    public int IKeyPolicy { get; set; }

    public int IKeyFlex { get; set; }

    public string CDescription { get; set; }

    public string CReference { get; set; }

    public int IDuration { get; set; }

    public int IPriority { get; set; }

    public int IEventCount { get; set; }

    public DateTime? DBegin { get; set; }

    public DateTime? DEnd { get; set; }

    public DateTime? DCompleted { get; set; }

    public int ICodeWorkFlowType { get; set; }

    public int ICodeWorkFlowStatus { get; set; }

    public int IKeyUserCreated { get; set; }

    public int IKeyUserNotify { get; set; }

    public int IPercentageCompleted { get; set; }

    public decimal YTotalRevenue { get; set; }

    public int IKeyProducerGroup { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}