// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class DlfAddressPartyLink
{
    public Guid GUidAddress { get; set; }

    public Guid GUidParty { get; set; }

    public Guid GUid { get; set; }
}