// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class DlfBalance
{
    public int IKeyBatch { get; set; }

    public int? IKeyId { get; set; }

    public int IKeyFile { get; set; }

    public int? IKeyProcess { get; set; }

    public DateTime? DRecord { get; set; }

    public int ICodeProcessResult { get; set; }

    public string CAccountNumber { get; set; }

    public int? ICodeAccountType { get; set; }

    public string CAccountTypeCode { get; set; }

    public string CAccountTypeDescription { get; set; }

    public int ICodeAccountValueType { get; set; }

    public int ICodeAccountStatus { get; set; }

    public string CAccountStatusCode { get; set; }

    public string CAccountStatusDescription { get; set; }

    public int ICodeAccountTaxStatus { get; set; }

    public int ICodeCompany { get; set; }

    public string CCompanyCode { get; set; }

    public string CCompanyDescription { get; set; }

    public DateTime? DBalanceDate { get; set; }

    public decimal? YCashBalance { get; set; }

    public decimal? YCashAvailable { get; set; }

    public decimal? YEquity { get; set; }

    public decimal? YMarketValue { get; set; }

    public decimal? YBuyingPower { get; set; }

    public decimal? YMarketValueShort { get; set; }

    public decimal? YMarketValueLong { get; set; }

    public decimal? YMarginBalance { get; set; }

    public decimal? YMarginMarketValue { get; set; }

    public decimal? YSmabalance { get; set; }

    public decimal? YMoneyMarketBalance { get; set; }

    public string COfficeNumber { get; set; }

    public string CRep1Code { get; set; }

    public string CRep1Fullname { get; set; }

    public bool BFlagRep1Organization { get; set; }

    public string CRep2Code { get; set; }

    public string CRep2Fullname { get; set; }

    public bool BFlagRep2Organization { get; set; }

    public string CMgr1Code { get; set; }

    public string CMgr1Fullname { get; set; }

    public bool BFlagMgr1Organization { get; set; }

    public int IKeyAccountInAa { get; set; }

    public int IKeyProducer1ReferenceInAa { get; set; }

    public int IKeyProducer2ReferenceInAa { get; set; }

    public int IKeyManager1ReferenceInAa { get; set; }

    public bool BFlagRepCode1NeedsValidation { get; set; }

    public bool BFlagRepCode2NeedsValidation { get; set; }

    public bool BFlagMgrCode1NeedsValidation { get; set; }

    public int IKeyProducer1InAa { get; set; }

    public int IKeyProducer2InAa { get; set; }

    public int IKeyManager1InAa { get; set; }

    public bool BFlagAccountNeedsValidation { get; set; }

    public string CReportMessage { get; set; }

    public int ICodeCustodian { get; set; }

    public string CCustodianCode { get; set; }

    public string CCustodianDescription { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}