// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class DlfCoverage
{
    public int IKeyBatch { get; set; }

    public int IKeyFile { get; set; }

    public int? IKeyProcess { get; set; }

    public Guid? GUidPolicy { get; set; }

    public int ICodeProcessResult { get; set; }

    public DateTime? DRecord { get; set; }

    public DateTime? DEffective { get; set; }

    public DateTime? DTermination { get; set; }

    public DateTime? DExpiration { get; set; }

    public string CPlanAbbreviation { get; set; }

    public string CPlanDescription { get; set; }

    public bool BFlagBaseCoverage { get; set; }

    public int ICodePlanType { get; set; }

    public string CPlanTypeCode { get; set; }

    public string CPlanTypeDescription { get; set; }

    public int ICodeProductClass { get; set; }

    public int ICodeFundingOption { get; set; }

    public int ICodeDeathBenefitOption { get; set; }

    public int ICodeDividendOption { get; set; }

    public string CDividendOptionCode { get; set; }

    public string CDividendOptionDescription { get; set; }

    public int ICodeStatus { get; set; }

    public string CStatusCode { get; set; }

    public string CStatusDescription { get; set; }

    public int ICodeApprovalBasis { get; set; }

    public string CApprovalBasisCode { get; set; }

    public string CApprovalBasisDescription { get; set; }

    public int ICodeSicknessEliminationPeriod { get; set; }

    public string CSicknessEliminationPeriodCode { get; set; }

    public string CSicknessEliminationPeriodDescription { get; set; }

    public int ICodeSicknessBenefitPeriod { get; set; }

    public string CSicknessBenefitPeriodCode { get; set; }

    public string CSicknessBenefitPeriodDescription { get; set; }

    public int ICodeBenefitMode { get; set; }

    public string CBenefitModeCode { get; set; }

    public string CBenefitModeDescription { get; set; }

    public int IIndicatorCode { get; set; }

    public string MBeneficiary { get; set; }

    public decimal YCashWithApp { get; set; }

    public decimal YBenefitAmount { get; set; }

    public decimal YBenefitAmountSickness { get; set; }

    public decimal YBenefitAmountAccident { get; set; }

    public decimal YAnnualPremium { get; set; }

    public decimal YModalPremium { get; set; }

    public decimal? YCashValue { get; set; }

    public decimal? YPremiumToDate { get; set; }

    public decimal YLastPremPaymentAmt { get; set; }

    public decimal? YLoanAmount { get; set; }

    public decimal? YMaxAvailableLoan { get; set; }

    public decimal? YSurrenderCharge { get; set; }

    public decimal? YSurrenderValue { get; set; }

    public int IKeyPlanInAa { get; set; }

    public bool BFlagPlanNeedsValidation { get; set; }

    public bool BFlagValidatePlan { get; set; }

    public string CReportMessage { get; set; }

    public string COccupationClass { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}