// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class DlfPositionSecuritySet
{
    public int IKeyProcess { get; set; }

    public int IKeySecurity { get; set; }

    public bool BFlagUpdate { get; set; }

    public bool BFlagProcessed { get; set; }

    public string CDescriptionAa { get; set; }

    public string CDescriptionDlf { get; set; }

    public int ICodeCompanyAa { get; set; }

    public int ICodeCompanyDfl { get; set; }

    public int ICodeNvstTypeAa { get; set; }

    public int ICodeNvstTypeDlf { get; set; }

    public int ICodeSectorAa { get; set; }

    public int ICodeSectorDlf { get; set; }

    public bool BFlagFixedAa { get; set; }

    public bool BFlagFixedDlf { get; set; }

    public bool BFlagFixedIncomeAa { get; set; }

    public bool BFlagFixedIncomeDlf { get; set; }

    public bool BFlagInterestBearingAa { get; set; }

    public bool BFlagInterestBearingDlf { get; set; }

    public DateTime? DMatureAa { get; set; }

    public DateTime? DMatureDlf { get; set; }

    public decimal NShareFactorAa { get; set; }

    public decimal NShareFactorDlf { get; set; }

    public decimal NPriceFactorAa { get; set; }

    public decimal NPriceFactorDlf { get; set; }

    public bool BFlagPoolAa { get; set; }

    public bool BFlagPoolDlf { get; set; }

    public DateTime? DRecAa { get; set; }

    public DateTime? DRecDlf { get; set; }

    public int IKeyModuleAa { get; set; }

    public string CSymbolAa { get; set; }

    public string CSymbolDlf { get; set; }

    public string CCusipAa { get; set; }

    public string CCusipDlf { get; set; }

    public string CCusipExtAa { get; set; }

    public string CCusipExtDlf { get; set; }

    public string COldCusipAa { get; set; }

    public string COldCusipExtAa { get; set; }

    public string CAlternateIdaa { get; set; }

    public string CAlternateIddlf { get; set; }

    public string COldAlternateIdaa { get; set; }
}