// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class DlfProcess
{
    public int IKeyId { get; set; }

    public int IKeyUser { get; set; }

    public int IKeyModule { get; set; }

    public DateTime? DStart { get; set; }

    public DateTime? DEnd { get; set; }

    public string CDescription { get; set; }

    public string CStats { get; set; }

    public int IKeyStart { get; set; }

    public int IKeyEnd { get; set; }

    public bool BFlagDeleteRecords { get; set; }

    public bool BFlagRecordsDeleted { get; set; }
}