// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class DlfPositionPositionSet
{
    public int IKeyId { get; set; }

    public int IKeyProcess { get; set; }

    public int IKeyNvst { get; set; }

    public int IKeySecurity { get; set; }

    public int IKeyPositionInAa { get; set; }

    public int IKeyReconcileInAa { get; set; }

    public int ICodeAcctValueType { get; set; }

    public int IKeyModuleInAa { get; set; }

    public DateTime? DValue { get; set; }

    public decimal NUnits { get; set; }

    public decimal NUnitsInAa { get; set; }

    public bool BFlagAdded { get; set; }

    public bool BFlagUpdated { get; set; }

    public int ICodePositionType { get; set; }

    public decimal NSharePrice { get; set; }

    public decimal NPoolFactor { get; set; }
}