// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class DlfPolicyPosition
{
    public int? IKeyId { get; set; }

    public int IKeyBatch { get; set; }

    public int IKeyFile { get; set; }

    public int? IKeyProcess { get; set; }

    public int ICodeProcessResult { get; set; }

    public DateTime? DRecord { get; set; }

    public DateTime? DPosition { get; set; }

    public DateTime? DPremiumPaidThru { get; set; }

    public string CPlanAbbreviation { get; set; }

    public string CPlanDescription { get; set; }

    public bool BFlagBaseCoverage { get; set; }

    public string CPolicyNumber { get; set; }

    public string CCertNumber { get; set; }

    public string CFundingAccount { get; set; }

    public int IKeyFundingAccount { get; set; }

    public int ICodeProductClass { get; set; }

    public int ICodeStatus { get; set; }

    public int ICodePlanType { get; set; }

    public string CPlanTypeCode { get; set; }

    public string CPlanTypeDescription { get; set; }

    public int ICodeCompany { get; set; }

    public string CCompanyCode { get; set; }

    public string CCompanyDescription { get; set; }

    public decimal YCashValue { get; set; }

    public decimal YSurrenderCharge { get; set; }

    public decimal YSurrenderValue { get; set; }

    public decimal YLoanAmount { get; set; }

    public decimal YMaxAvailableLoan { get; set; }

    public decimal YPremiumToDate { get; set; }

    public int IKeyPlanInAa { get; set; }

    public bool BFlagPlanNeedsValidation { get; set; }

    public bool BFlagValidatePlan { get; set; }

    public string CRep1Code { get; set; }

    public string CRep1Fullname { get; set; }

    public bool BFlagRep1Organization { get; set; }

    public string CRep2Code { get; set; }

    public string CRep2Fullname { get; set; }

    public bool BFlagRep2Organization { get; set; }

    public string CMgr1Code { get; set; }

    public string CMgr1Fullname { get; set; }

    public bool BFlagMgr1Organization { get; set; }

    public int IKeyProducer1ReferenceInAa { get; set; }

    public int IKeyProducer2ReferenceInAa { get; set; }

    public int IKeyManager1ReferenceInAa { get; set; }

    public bool BFlagRepCode1NeedsValidation { get; set; }

    public bool BFlagRepCode2NeedsValidation { get; set; }

    public bool BFlagMgrCode1NeedsValidation { get; set; }

    public int IKeyProducer1InAa { get; set; }

    public int IKeyProducer2InAa { get; set; }

    public int IKeyManager1InAa { get; set; }

    public int IKeyPolicyInAa { get; set; }

    public int IKeyBaseCoverageInAa { get; set; }

    public int IKeyCoverageInAa { get; set; }

    public bool BFlagPolicyNeedsValidation { get; set; }

    public string CReportMessage { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}