// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class DlfPartyRegistrationLink
{
    public Guid GuidParty { get; set; }

    public Guid GuidRegistration { get; set; }

    public int ICodeRelationship { get; set; }

    public Guid Guid { get; set; }
}