// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class DlfPartyPolicyLink
{
    public Guid GuidParty { get; set; }

    public Guid GuidPolicy { get; set; }

    public int ICodeRelationship { get; set; }

    public Guid Guid { get; set; }
}