// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class DlfPositionAccountSet
{
    public string CAccount { get; set; }

    public int IKeyAccount { get; set; }

    public int IKeyProcess { get; set; }

    public int IKeyClient { get; set; }

    public int IKeyProducer1InAa { get; set; }

    public bool BFlagAdd { get; set; }

    public bool BFlagUpdate { get; set; }

    public bool BflagProcessed { get; set; }

    public bool BFlagDifferentModule { get; set; }

    public int ICodeAccountTypeAa { get; set; }

    public int ICodeAccountTypeDlf { get; set; }

    public DateTime? DRecordDlf { get; set; }

    public DateTime? DPositionDateAa { get; set; }

    public int ICodeObjectiveAa { get; set; }

    public int ICodeObjectiveDlf { get; set; }

    public int IKeyPrimaryProducerAa { get; set; }

    public int IKeyProducer1Dlf { get; set; }

    public int IKeyProducer1Aa { get; set; }

    public int IKeyManager1Aa { get; set; }

    public int ICodeCustodianAa { get; set; }

    public int ICodeCustodianDlf { get; set; }

    public int ICodeBasisTypeAa { get; set; }

    public int ICodeBasisTypeDlf { get; set; }

    public int ICodeTaxStatusAa { get; set; }

    public int ICodeTaxStatusDlf { get; set; }

    public int ICodeStatusAa { get; set; }

    public int ICodeStatusDlf { get; set; }

    public int IKeyModuleAa { get; set; }

    public bool BFlagRoraa { get; set; }

    public bool BFlagPositionOnlyAa { get; set; }

    public bool BFlagPositionOnlyDlf { get; set; }
}