// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class DlfPositionInvestmentSet
{
    public int IKeyId { get; set; }

    public int IKeyProcess { get; set; }

    public int IKeyAccountInAa { get; set; }

    public int IKeyNvstInAa { get; set; }

    public int IKeySecurityInAa { get; set; }

    public bool BFlagAdd { get; set; }

    public bool BFlagUpdate { get; set; }

    public bool BFlagProcessed { get; set; }

    public DateTime? DAcquiredDlf { get; set; }

    public DateTime? DEffecitiveAa { get; set; }

    public int ICodeBasisTypeDlf { get; set; }

    public int ICodeBasisTypeAa { get; set; }

    public int IKeyModuleAa { get; set; }

    public int IKeyDlffileCreated { get; set; }
}