// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class DlfRegistration
{
    public int IKeyBatch { get; set; }

    public int? IKeyId { get; set; }

    public int IKeyFile { get; set; }

    public int? IKeyProcess { get; set; }

    public DateTime? DRecord { get; set; }

    public int ICodeProcessResult { get; set; }

    public string CAccountNumber { get; set; }

    public DateTime? DAcquiredAccount { get; set; }

    public DateTime? DAcquiredInvestment { get; set; }

    public string CRegLine1 { get; set; }

    public string CRegLine2 { get; set; }

    public string CRegLine3 { get; set; }

    public string CRegLine4 { get; set; }

    public string CRegLine5 { get; set; }

    public string CRegLine6 { get; set; }

    public string CRegLine7 { get; set; }

    public int ICodeAccountObjective { get; set; }

    public string CAccountObjectiveCode { get; set; }

    public string CAccountObjectiveDescription { get; set; }

    public int ICodeAccountType { get; set; }

    public string CAccountTypeCode { get; set; }

    public string CAccountTypeDescription { get; set; }

    public int ICodeAccountStatus { get; set; }

    public string CAccountStatusCode { get; set; }

    public string CAccountStatusDescription { get; set; }

    public int ICodeAccountTaxStatus { get; set; }

    public string CTaxidInvestor { get; set; }

    public DateTime? DInvestorDob { get; set; }

    public string CRep1Code { get; set; }

    public string CRep1Fullname { get; set; }

    public bool BFlagRep1Organization { get; set; }

    public string CRep2Code { get; set; }

    public string CRep2Fullname { get; set; }

    public bool BFlagRep2Organization { get; set; }

    public string CMgr1Code { get; set; }

    public string CMgr1Fullname { get; set; }

    public bool BFlagMgr1Organization { get; set; }

    public string CSymbol { get; set; }

    public string CDescription { get; set; }

    public string CCusip { get; set; }

    public string CCusipExt { get; set; }

    public string CAlternateId { get; set; }

    public int ICodeCompany { get; set; }

    public string CCompanyCode { get; set; }

    public string CCompanyDescription { get; set; }

    public int ICodeCategory { get; set; }

    public string CCategoryCode { get; set; }

    public string CCategoryDescription { get; set; }

    public int ICodeSector { get; set; }

    public string CSectorCode { get; set; }

    public string CSectorDescription { get; set; }

    public int ICodeInvType { get; set; }

    public string CInvTypeCode { get; set; }

    public string CInvTypeDescription { get; set; }

    public bool? BFlagFixedValue { get; set; }

    public bool? BFlagMoneyMarket { get; set; }

    public int ICodeBasisType { get; set; }

    public decimal YContributions { get; set; }

    public decimal YCostBasis { get; set; }

    public int IKeyAccountInAa { get; set; }

    public int IKeySecurityInAa { get; set; }

    public bool BFlagSecurityFoundViaOld { get; set; }

    public int IKeyProducer1ReferenceInAa { get; set; }

    public int IKeyProducer2ReferenceInAa { get; set; }

    public int IKeyManager1ReferenceInAa { get; set; }

    public bool BFlagSecurityNeedsValidation { get; set; }

    public bool BFlagValidateSecurity { get; set; }

    public bool BFlagRepCode1NeedsValidation { get; set; }

    public bool BFlagRepCode2NeedsValidation { get; set; }

    public bool BFlagMgrCode1NeedsValidation { get; set; }

    public int IKeyProducer1InAa { get; set; }

    public int IKeyProducer2InAa { get; set; }

    public int IKeyManager1InAa { get; set; }

    public bool BFlagAccountNeedsValidation { get; set; }

    public string CReportMessage { get; set; }

    public int ICodeCustodian { get; set; }

    public string CCustodianCode { get; set; }

    public string CCustodianDescription { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}