// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class DstcusipChange
{
    public int IKeyId { get; set; }

    public string COldManagementCode { get; set; }

    public string COldCusip { get; set; }

    public string COldFundCode { get; set; }

    public string COldFundName { get; set; }

    public string COldProdName { get; set; }

    public string CNewManagementCode { get; set; }

    public string CNewCusip { get; set; }

    public string CNewFundCode { get; set; }

    public string CNewFundName { get; set; }

    public string CNewProdName { get; set; }

    public string CEffectiveDate { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public int IRecVersion { get; set; }

    public Guid GUid { get; set; }
}