// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class InfinetLink
{
    public int IKeyId { get; set; }

    public int IKeyInfinetContact { get; set; }

    public int IkeyAaname { get; set; }

    public int IKeyCtascustomer { get; set; }

    public int IKeyInfinetGroup { get; set; }

    public DateTime? DateSynched { get; set; }

    public bool? BUseTaxIdinSynch { get; set; }

    public bool BArchived { get; set; }
}