// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class InfinetLinkNewAa
{
    public int IKeyId { get; set; }

    public int IKeyAaname { get; set; }

    public string CTaxId { get; set; }

    public string CPassport { get; set; }

    public string CDriversLicense { get; set; }
}