// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class InfinetLinkExtension
{
    public int IKeyId { get; set; }

    public int IkeyInfinetLink { get; set; }

    public string CRepCode { get; set; }

    public string CTaxIdinfinet { get; set; }

    public string CTaxidAa { get; set; }

    public string CPassportAa { get; set; }

    public string CdriversLicenseAa { get; set; }

    public bool BFlagUpdatedInfinet { get; set; }

    public bool BFlagUpdatedAa { get; set; }

    public bool BFlagTaxidChangeInfinet { get; set; }

    public bool BFlagTaxidChangeAa { get; set; }
}