// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_AnalyzeInvestmentDataResult
    {
        public int? iProblem { get; set; }
        [Column("nSumOfOpenLotUnits", TypeName = "decimal(16,6)")]
        public decimal? nSumOfOpenLotUnits { get; set; }
        [Column("nInvestmentUnits", TypeName = "decimal(16,6)")]
        public decimal? nInvestmentUnits { get; set; }
        public DateTime? dLiquidatedDate { get; set; }
        public DateTime? dInit { get; set; }
        public DateTime? dEarliestTransaction { get; set; }
        public string cEarliestTransactionType { get; set; }
    }
}
