// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_AACalEventDataGetByCriteriaWithNameResult
    {
        public int EventKeyID { get; set; }
        public int DetailKeyID { get; set; }
        public int ExceptionKeyID { get; set; }
        public Guid guidEvent { get; set; }
        public int iRecurOption { get; set; }
    }
}
