// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_CheckCalendarEventResult
    {
        public string cEventType { get; set; }
        public int ipriority { get; set; }
        public int iDetailKeyID { get; set; }
        public int iKeyEvent { get; set; }
        public DateTime? dBeginDate { get; set; }
        public DateTime? dBegin { get; set; }
        public string cdescription { get; set; }
        public string cwith { get; set; }
        public bool bFlagCompleted { get; set; }
        public bool bFlagAcknowledged { get; set; }
        public int iNotificationKeyID { get; set; }
        public DateTime? dDue { get; set; }
        public int? iDayDiff { get; set; }
        public string cDayDiff { get; set; }
    }
}
