// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_DLFGetProcessReportStatsResult
    {
        public int iKeyID { get; set; }
        public int? iRegOK { get; set; }
        public int? iRegUnassigned { get; set; }
        public int? iRegException { get; set; }
        public int? iRegIgnored { get; set; }
        public int? iRegNeedsAttention { get; set; }
        public int? iRegTotal { get; set; }
        public int? iTranOK { get; set; }
        public int? iTranException { get; set; }
        public int? iTranIgnored { get; set; }
        public int? iTranNeedsAttention { get; set; }
        public int? iTranUnassigned { get; set; }
        public int? iTranTotal { get; set; }
        public int? iPosOK { get; set; }
        public int? iPosException { get; set; }
        public int? iPosIgnored { get; set; }
        public int? iPosNeedsAttention { get; set; }
        public int? iPosUnassigned { get; set; }
        public int? iPosTotal { get; set; }
        public int? iOutOfBalance { get; set; }
        public int? iReinvestmentReconciles { get; set; }
        public int? iBalOK { get; set; }
        public int? iBalException { get; set; }
        public int? iBalIgnored { get; set; }
        public int? iBalNeedsAttention { get; set; }
        public int? iBalTotal { get; set; }
        public int? iPolicyOK { get; set; }
        public int? iPolicyUnassigned { get; set; }
        public int? iPolicyException { get; set; }
        public int? iPolicyIgnored { get; set; }
        public int? iPolicyNeedsAttention { get; set; }
        public int? iPolicyTotal { get; set; }
        public int? iCoverageOK { get; set; }
        public int? iCoverageUnassigned { get; set; }
        public int? iCoverageException { get; set; }
        public int? iCoverageIgnored { get; set; }
        public int? iCoverageNeedsAttention { get; set; }
        public int? iCoverageTotal { get; set; }
        public int? iPolicyPositionOK { get; set; }
        public int? iPolicyPositionUnassigned { get; set; }
        public int? iPolicyPositionException { get; set; }
        public int? iPolicyPositionIgnored { get; set; }
        public int? iPolicyPositionNeedsAttention { get; set; }
        public int? iPolicyPositionTotal { get; set; }
    }
}
