// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_DlfGetKeysToProcessResult
    {
        public int? iKeyId { get; set; }
        public int iKeyFile { get; set; }
        public int iKeyBatch { get; set; }
        public int iCodeProcessResult { get; set; }
        public int iKeyAccountInAA { get; set; }
    }
}
