// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_dlfGetRepCodesNotFoundResult
    {
        public string cRep1Code { get; set; }
        public string cRep1Fullname { get; set; }
        public string cCompanyCode { get; set; }
        public string cCompanyDescription { get; set; }
    }
}
