// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_FinanceLogixExportByNameResult
    {
        public Guid NameGUID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string TaxID { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string EmailAddress { get; set; }
        public string Website { get; set; }
        public DateTime? DateOfMarriage { get; set; }
        public Guid? SpouseGUID { get; set; }
        public string SpouseFullName { get; set; }
        public string SpouseFirstName { get; set; }
        public string SpouseLastName { get; set; }
        public string SpouseTaxID { get; set; }
        public DateTime? SpouseDateOfBirth { get; set; }
        public string address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipPostalCode { get; set; }
        public string PhoneType { get; set; }
        public string PhoneNum { get; set; }
        public string PhoneExt { get; set; }
        public string FullPhone { get; set; }
        public string PhoneAreaCode { get; set; }
    }
}
