// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetMessagesByUserIDResult
    {
        public int ikeyid { get; set; }
        public string csent { get; set; }
        public DateTime? dsent { get; set; }
        public bool bflagsenderdeleted { get; set; }
        public bool bflagreceiverdeleted { get; set; }
        public string clientname { get; set; }
        public string csenderfullname { get; set; }
        public string mtext { get; set; }
        public int ikeysource { get; set; }
        public int? ikeyclient { get; set; }
        public int? ikeytopic { get; set; }
    }
}
