// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetViewClientDataCountResult
    {
        public int? coverages { get; set; }
        public int? annuitycoverages { get; set; }
        public int? policies { get; set; }
        public int? annuitypolicies { get; set; }
        public int? accounts { get; set; }
        public int? annuityaccounts { get; set; }
        public int? notes { get; set; }
        public int? notes_policy { get; set; }
        public int? notes_account { get; set; }
        public int? markets { get; set; }
        public int? links { get; set; }
        public int? households { get; set; }
        public int? householdmembers { get; set; }
        public int? files { get; set; }
        public int? events { get; set; }
        public int? forms { get; set; }
        public int? newbiz { get; set; }
        public int? workflow { get; set; }
        public int? flex { get; set; }
    }
}
