// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetNoteTopicListViewScreenMessagesResult
    {
        public int iKeyID { get; set; }
        public string cDescription { get; set; }
        public string NoteTypeDesc { get; set; }
        public int? iNoteCount { get; set; }
        public DateTime? began { get; set; }
        public DateTime? latest { get; set; }
        public string latestby { get; set; }
        public int iCodeNoteType { get; set; }
        public string ReferenceType { get; set; }
        public int? LatestNoteKey { get; set; }
        public int iKeyWorkflow { get; set; }
    }
}
