// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetUserSyncOptionsByCalendarManyResult
    {
        public int? UserKeyID { get; set; }
        public int? CalendarKeyID { get; set; }
        public int? SyncOption { get; set; }
        public bool? RealTimeExportEnabled { get; set; }
        public string UserName { get; set; }
        public Guid? UserGuid { get; set; }
    }
}
