// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetViewPolicyDataPolicyResult
    {
        public int iKeyID { get; set; }
        public string cPolicyNumber { get; set; }
        public int iKeyPrimaryClient { get; set; }
        public DateTime? dEffective { get; set; }
        public DateTime? dComplete { get; set; }
        public DateTime? dIssue { get; set; }
        public decimal yTotalAnnualPremBase { get; set; }
        public decimal yTotalAnnualPremExcess1 { get; set; }
        public decimal yTotalAnnualPremExcess2 { get; set; }
        public decimal yTotalAnnualPremRider { get; set; }
        public decimal yTotalAnnualPrem { get; set; }
        public decimal yTotalModalPrem { get; set; }
        public decimal yTotalCashVal { get; set; }
        public decimal yTotalOtherValue { get; set; }
        public decimal yTotalLoans { get; set; }
        public decimal yTotalSurrenderCharge { get; set; }
        public decimal ySurrenderValue { get; set; }
        public decimal yNetCashValue { get; set; }
        public decimal yNetBenefit { get; set; }
        public string CompanyDesc { get; set; }
        public string StatusDesc { get; set; }
        public string PremiumModeDesc { get; set; }
        public string TobaccoDesc { get; set; }
        public string OwnerName { get; set; }
        public string GroupWithName { get; set; }
        public string ProducerName { get; set; }
        public int ProducerKeyID { get; set; }
        public int iKeyBaseCoverage { get; set; }
        public int? BaseCoverageClass { get; set; }
        public bool? PrimaryClientIsOrg { get; set; }
        public bool PrimaryClientIsHOH { get; set; }
        public int PrimaryClientProducerKeyID { get; set; }
        public int PrimaryClientProducerDefaultManagerKeyID { get; set; }
        public string SubtypeDesc { get; set; }
        public int PrimaryClientHouseholdKeyID { get; set; }
        public int? BaseCoverageSeriesKeyID { get; set; }
        public string OwnerPrimaryProducerAdvisorVaultUserName { get; set; }
        public string OwnerPrimaryProducerName { get; set; }
        public string OwnerPrimaryEmailAddress { get; set; }
        public string OwnerFirstName { get; set; }
        public string OwnerLastName { get; set; }
        public string OwnerPrimaryPhone { get; set; }
    }
}
