// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetRORNavDataSetResult
    {
        public int ikeysymbol { get; set; }
        public DateTime? dActivity { get; set; }
        public int nEODPrice { get; set; }
        public int nBODPrice { get; set; }
    }
}
