// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetInsuranceExportDataResult
    {
        public int? UniquePolicyID { get; set; }
        public int UniqueCoverageID { get; set; }
        public int? UniqueNameID { get; set; }
        public string PolicyProducer1 { get; set; }
        public int? PolicyProducerNameID1 { get; set; }
        [Column("PolicyProducer1Split", TypeName = "decimal(13,7)")]
        public decimal? PolicyProducer1Split { get; set; }
        [Column("PolicyProducer1Renew", TypeName = "decimal(13,7)")]
        public decimal? PolicyProducer1Renew { get; set; }
        public int? PolicyProducer1UniqueID { get; set; }
        public string PolicyProducer2 { get; set; }
        public int? PolicyProducerNameID2 { get; set; }
        [Column("PolicyProducer2Split", TypeName = "decimal(13,7)")]
        public decimal? PolicyProducer2Split { get; set; }
        [Column("PolicyProducer2Renew", TypeName = "decimal(13,7)")]
        public decimal? PolicyProducer2Renew { get; set; }
        public int? PolicyProducer2UniqueID { get; set; }
        public string PolicyProducer3 { get; set; }
        public int? PolicyProducerNameID3 { get; set; }
        [Column("PolicyProducer3Split", TypeName = "decimal(13,7)")]
        public decimal? PolicyProducer3Split { get; set; }
        [Column("PolicyProducer3Renew", TypeName = "decimal(13,7)")]
        public decimal? PolicyProducer3Renew { get; set; }
        public int? PolicyProducer3UniqueID { get; set; }
        public string PolicyProducer4 { get; set; }
        public int? PolicyProducerNameID4 { get; set; }
        [Column("PolicyProducer4Split", TypeName = "decimal(13,7)")]
        public decimal? PolicyProducer4Split { get; set; }
        [Column("PolicyProducer4Renew", TypeName = "decimal(13,7)")]
        public decimal? PolicyProducer4Renew { get; set; }
        public int? PolicyProducer4UniqueID { get; set; }
        public string PolicyManager1 { get; set; }
        public int? PolicyManagerNameID1 { get; set; }
        [Column("PolicyManager1Split", TypeName = "decimal(13,7)")]
        public decimal? PolicyManager1Split { get; set; }
        [Column("PolicyManager1Renew", TypeName = "decimal(13,7)")]
        public decimal? PolicyManager1Renew { get; set; }
        public int? PolicyManager1UniqueID { get; set; }
        public string PolicyManager2 { get; set; }
        public int? PolicyManagerNameID2 { get; set; }
        [Column("PolicyManager2Split", TypeName = "decimal(13,7)")]
        public decimal? PolicyManager2Split { get; set; }
        [Column("PolicyManager2Renew", TypeName = "decimal(13,7)")]
        public decimal? PolicyManager2Renew { get; set; }
        public int? PolicyManager2UniqueID { get; set; }
        public string PolicyManager3 { get; set; }
        public int? PolicyManagerNameID3 { get; set; }
        [Column("PolicyManager3Split", TypeName = "decimal(13,7)")]
        public decimal? PolicyManager3Split { get; set; }
        [Column("PolicyManager3Renew", TypeName = "decimal(13,7)")]
        public decimal? PolicyManager3Renew { get; set; }
        public int? PolicyManager3UniqueID { get; set; }
        public string PolicyManager4 { get; set; }
        public int? PolicyManagerNameID4 { get; set; }
        [Column("PolicyManager4Split", TypeName = "decimal(13,7)")]
        public decimal? PolicyManager4Split { get; set; }
        [Column("PolicyManager4Renew", TypeName = "decimal(13,7)")]
        public decimal? PolicyManager4Renew { get; set; }
        public int? PolicyManager4UniqueID { get; set; }
        public string PolicyPayor { get; set; }
        public DateTime? PolicyPayorDateOfBirth { get; set; }
        public string PolicyOwner { get; set; }
        public string PolicyOwnerSortName { get; set; }
        public string PolicyOwnerFirstname { get; set; }
        public string PolicyOwnerLastname { get; set; }
        public DateTime? PolicyOwnerDateOfBirth { get; set; }
        public string PolicyOwnerEmail { get; set; }
        public string CoverageBeneficiaryLong { get; set; }
        public string CoverageBeneficiaryNamed { get; set; }
        public string PolicyCompany { get; set; }
        public string PolicyCompanyAbbr { get; set; }
        public string PolicyNumber { get; set; }
        public string CertificateID { get; set; }
        public string CaseReference { get; set; }
        public DateTime? PolicyValuationDate { get; set; }
        public string CoverageClass { get; set; }
        public string CoverageClassAbbr { get; set; }
        public string CoveragePlan { get; set; }
        public string CoveragePlanAbbr { get; set; }
        public string CoverageTypeDesc { get; set; }
        public string CoverageType { get; set; }
        public int? UniqueCoverageTypeID { get; set; }
        public string PolicyTobaccoDesc { get; set; }
        public string PolicyTobacco { get; set; }
        public int? UniquePolicyTobaccoID { get; set; }
        public decimal CoverageBenefit { get; set; }
        public decimal CoverageCashWithApp { get; set; }
        public string CoverageBenefitMode { get; set; }
        public string PrimaryCoverage { get; set; }
        public string QualifiedPlanType { get; set; }
        public string CoverageBenefitPeriod { get; set; }
        public string CoverageBenefitPeriodSick { get; set; }
        public string CoverageBenefitPeriodAccident { get; set; }
        public string CoverageElimPeriodSick { get; set; }
        public string CoverageElimPeriodAccident { get; set; }
        public decimal CoverageBenefitAccident { get; set; }
        public decimal CoverageBenefitSick { get; set; }
        public int CoverageParticipants { get; set; }
        public string PremiumMode { get; set; }
        public string PremiumModeAbbr { get; set; }
        public decimal? PremiumPolicyModalTotal { get; set; }
        public decimal? PremiumPolicyAnnualTotal { get; set; }
        public decimal CoverageLastPaidAmount { get; set; }
        public int? UniquePolicyInsuredNameID { get; set; }
        public int UniqueCoverageInsuredNameID { get; set; }
        public string PrimaryInsured { get; set; }
        public string PrimaryInsuredSortName { get; set; }
        public string PrimaryInsuredFirstname { get; set; }
        public string PrimaryInsuredLastname { get; set; }
        public DateTime? PrimaryInsuredDateOfBirth { get; set; }
        public int? PrimaryInsuredHouseholdID { get; set; }
        public int? PrimaryInsuredHeadOfHouseholdID { get; set; }
        public int? OwnerHouseholdID { get; set; }
        public int? OwnerHeadOfHouseholdID { get; set; }
        public string CoverageStatus { get; set; }
        public string CoverageApprovalBasis { get; set; }
        public string RenewalProvision { get; set; }
        public DateTime? CoverageSubmitDate { get; set; }
        public string CoverageSubmitMonthYear { get; set; }
        public DateTime? PolicyIssueDate { get; set; }
        public string PolicyIssueMonthYear { get; set; }
        public DateTime? CoverageEffectiveDate { get; set; }
        public string CoverageEffectiveMonthYear { get; set; }
        public string CoverageEffectiveMonthDaySort { get; set; }
        public string CoverageEffectiveMonthDay { get; set; }
        public DateTime? CoverageCompletedDate { get; set; }
        public string CoverageCompletedMonthYear { get; set; }
        public DateTime? CoverageExpirationDate { get; set; }
        public string CoverageExpirationMonthYear { get; set; }
        public DateTime? CoverageTerminationDate { get; set; }
        public string CoverageTerminationMonthYear { get; set; }
        public DateTime? CoverageConversionDate { get; set; }
        public string ConversionMonthYear { get; set; }
        public DateTime? CoverageRenewalDate { get; set; }
        public string CoverageRenewalMonthYear { get; set; }
        public double? CoverageYear { get; set; }
        public decimal PremiumCoverageBaseAnnual { get; set; }
        public decimal PremiumCoverageExcessAnnual1 { get; set; }
        public decimal PremiumCoverageExcessAnnual2 { get; set; }
        public decimal PremiumCoverageAnnualTotal { get; set; }
        public decimal PremiumCoverageModalTotal { get; set; }
        public string CoverageDividendOption { get; set; }
        public string FundingOption { get; set; }
        public decimal CoverageCashValue { get; set; }
        public decimal CoverageNetCashValue { get; set; }
        public decimal CoverageOtherValue { get; set; }
        public decimal CoverageSurrenderCharge { get; set; }
        public decimal? CoverageSurrenderValue { get; set; }
        public decimal CoverageLoanAmount { get; set; }
        public decimal? PolicyLoanAmount { get; set; }
        public decimal? PolicySurrenderCharge { get; set; }
        public decimal? PolicySurrenderValue { get; set; }
        public decimal? PolicyNetCashValue { get; set; }
        public decimal? PolicyNetBenefit { get; set; }
        public decimal? PolicyPremiumToDate { get; set; }
        public DateTime? PremiumLastPaidDate { get; set; }
        public DateTime? PremiumsPaidThruDate { get; set; }
        public DateTime? PremiumNextDueDate { get; set; }
        public string StatusPolicy { get; set; }
        public string CoverageUnderwriter { get; set; }
        public decimal CoverageTotalRiderCashValue { get; set; }
        public decimal CoverageTotalRiderLoanAmount { get; set; }
        public decimal CommissionCoverage1stYrTotal { get; set; }
        public decimal? CommissionPolicy1stYrTotal { get; set; }
        public string GroupMasterCoverage { get; set; }
        public int GroupMasterCoverageUniqueID { get; set; }
        public string AccountNumber { get; set; }
        public string AccountType { get; set; }
        public string AnnuitySurrenderPeriod { get; set; }
        [Column("CoverageFlexField01Numeric", TypeName = "decimal(13,2)")]
        public decimal? CoverageFlexField01Numeric { get; set; }
        [Column("CoverageFlexField02Numeric", TypeName = "decimal(13,2)")]
        public decimal? CoverageFlexField02Numeric { get; set; }
        [Column("CoverageFlexField03Numeric", TypeName = "decimal(13,2)")]
        public decimal? CoverageFlexField03Numeric { get; set; }
        [Column("CoverageFlexField04Numeric", TypeName = "decimal(13,2)")]
        public decimal? CoverageFlexField04Numeric { get; set; }
        [Column("CoverageFlexField05Numeric", TypeName = "decimal(16,6)")]
        public decimal? CoverageFlexField05Numeric { get; set; }
        [Column("CoverageFlexField06Numeric", TypeName = "decimal(16,6)")]
        public decimal? CoverageFlexField06Numeric { get; set; }
        public int? CoverageFlexField07Numeric { get; set; }
        public int? CoverageFlexField08Numeric { get; set; }
        public string CoverageFlexField09Text { get; set; }
        public string CoverageFlexField10Text { get; set; }
        public string CoverageFlexField11Text { get; set; }
        public string CoverageFlexField12Text { get; set; }
        public DateTime? CoverageFlexField13Date { get; set; }
        public DateTime? CoverageFlexField14Date { get; set; }
        public DateTime? CoverageFlexField15Date { get; set; }
        public DateTime? CoverageFlexField16Date { get; set; }
        public string CoverageFlexField17Text { get; set; }
        public string CoverageFlexField18Text { get; set; }
        public string CoverageFlexField19Text { get; set; }
        public string CoverageFlexField20Text { get; set; }
        public DateTime? CoverageFlexField21Date { get; set; }
        public DateTime? CoverageFlexField22Date { get; set; }
        public string CoverageFlexField23Text { get; set; }
        public string CoverageFlexField24Text { get; set; }
        public string CoverageFlexField25Text { get; set; }
        public string CoverageFlexField26Text { get; set; }
        public string CoverageFlexField27Text { get; set; }
        public string CoverageFlexField28Text { get; set; }
        public string CoverageFlexField29Text { get; set; }
        public string CoverageFlexField30Text { get; set; }
    }
}
