// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetHouseholdInfoByClientIDResult
    {
        public Guid MembergUID { get; set; }
        public bool? MemberOrg { get; set; }
        public bool MemberDependent { get; set; }
        public string MemberFullName { get; set; }
        public string MemberFirstName { get; set; }
        public string MemberMiddleName { get; set; }
        public string MemberLastName { get; set; }
        public string MemberMiddleINITIAL { get; set; }
        public string MemberRelationship { get; set; }
        public DateTime? MemberDateOfBirth { get; set; }
        public int? MemberAgeActual { get; set; }
        public int? MemberAgeNearest { get; set; }
        public string MemberGender { get; set; }
        public string MemberIndustry { get; set; }
        public string MemberMaritalStatus { get; set; }
        public string MemberTobacco { get; set; }
        public string MemberOccupation { get; set; }
        public string MemberTaxID { get; set; }
        public string MemberCitizenship { get; set; }
        public string MemberPassport { get; set; }
        public DateTime? MemberPassportExpiration { get; set; }
        public DateTime? MemberPassportIssueDate { get; set; }
        public string MemberGreencard { get; set; }
        public DateTime? MemberGreencardExpiration { get; set; }
        public DateTime? MemberGreencardIssueDate { get; set; }
        public string MemberDriversLicense { get; set; }
        public DateTime? MemberDriversLicenseExpiration { get; set; }
        public DateTime? MemberDriversLicenseIssueDate { get; set; }
        public string MemberPhoneLocation { get; set; }
        public string MemberPhoneContact { get; set; }
        public string MemberPhoneCountryCode { get; set; }
        public string MemberPhoneAreaCode { get; set; }
        public string MemberPhoneNumber { get; set; }
        public string MemberPhoneExtension { get; set; }
        public string MemberFullPhone { get; set; }
        public string MemberGreeting { get; set; }
        public string MemberAddressLocation { get; set; }
        public string MemberAddress1 { get; set; }
        public string MemberAddress2 { get; set; }
        public string MemberAddress3 { get; set; }
        public string MemberCity { get; set; }
        public string MemberState { get; set; }
        public string MemberZipCode { get; set; }
        public string MemberRegion { get; set; }
        public string MemberCountry { get; set; }
        public string MemberCarrierRoute { get; set; }
        public string MemberDeliveryPoint { get; set; }
    }
}
