// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetOutlookEntryIDCalendarRowByKeyAALinkAndStoreKeyIDResult
    {
        public int iKeyId { get; set; }
        public int iKeyStore { get; set; }
        public int iKeyAALink { get; set; }
        public string cOutlookItemEntryID { get; set; }
        public DateTime? dLastSynch { get; set; }
        public string cWhoChange { get; set; }
        public DateTime? dLastChange { get; set; }
        public string cWhoAdded { get; set; }
        public DateTime? dWhenAdded { get; set; }
    }
}
