// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetViewClientNameTypesResult
    {
        public string NmTypeDesc { get; set; }
        public int ikeyid { get; set; }
        public int iSortOrder { get; set; }
    }
}
