// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetNotesListViewScreenAndReportResult
    {
        public int iKeyID { get; set; }
        public string cPolicyNumber { get; set; }
        public string PolicyNum { get; set; }
        public string Series { get; set; }
        public int? iNoteCount { get; set; }
        public DateTime? began { get; set; }
        public DateTime? latest { get; set; }
        public string latestby { get; set; }
        public DateTime? dFollowup { get; set; }
        public string FollowupAssignedTo { get; set; }
        public bool? FollowupCompleted { get; set; }
        public int? LatestNoteKey { get; set; }
        public int? LatestFollowupDetailKey { get; set; }
        public bool GroupMasterCoverage { get; set; }
    }
}
