// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetSummedNvstValuesResult
    {
        [Column("nTotalShares", TypeName = "decimal(38,6)")]
        public decimal? nTotalShares { get; set; }
        [Column("nRealGain", TypeName = "decimal(38,11)")]
        public decimal? nRealGain { get; set; }
        public decimal? yInterestTotal { get; set; }
        public decimal? yCgLongPaidOut { get; set; }
        public decimal? yCgLongReinvest { get; set; }
        public decimal? yCgShortPaidOut { get; set; }
        public decimal? yCgShortReinvest { get; set; }
        public decimal? yInterestPaidOut { get; set; }
        public decimal? yInterestReinvest { get; set; }
        public decimal? yDividendPaidOut { get; set; }
        public decimal? yDividendReinvest { get; set; }
        public decimal? yMoneyIn { get; set; }
        public decimal? yMoneyOut { get; set; }
        public decimal? yClientFlowIn { get; set; }
        public decimal? yClientFlowOut { get; set; }
        public decimal? yClientFlowNet { get; set; }
        public decimal? yOutsideFlowIn { get; set; }
        public decimal? yOutSideFlowOut { get; set; }
        public decimal? yOutSideFlowNet { get; set; }
        public decimal? yNetTransfers { get; set; }
        public decimal? yNetExpenses { get; set; }
        public decimal? yNetAdjustments { get; set; }
        public decimal? yDistPaidOut { get; set; }
        public decimal? yDistReinvested { get; set; }
    }
}
