// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetCostBasisAverageForNvstResult
    {
        public DateTime? dTrandate { get; set; }
        public DateTime? dSettle { get; set; }
        public string cDescription { get; set; }
        [Column("nshareprice", TypeName = "decimal(16,6)")]
        public decimal nshareprice { get; set; }
        [Column("nshares", TypeName = "decimal(16,6)")]
        public decimal nshares { get; set; }
        [Column("nShareBasis", TypeName = "decimal(16,6)")]
        public decimal nShareBasis { get; set; }
        public decimal yPrincipal { get; set; }
        public decimal yClientTotal { get; set; }
        public decimal yBasisIn { get; set; }
        public decimal yBasisOut { get; set; }
        public decimal? Basis { get; set; }
        public decimal CumulativeBasis { get; set; }
        public decimal? Income { get; set; }
    }
}
