// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetViewPolicyDataCountResult
    {
        public int? coverages { get; set; }
        public int? producers { get; set; }
        public int? files { get; set; }
        public int? relations { get; set; }
        public int? riders { get; set; }
        public int? newbiz { get; set; }
        public int? comms { get; set; }
        public int? workflow { get; set; }
    }
}
