// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetViewClientAddressesResult
    {
        public int ikeyid { get; set; }
        public int iCodeAddress { get; set; }
        public string AddrDesc { get; set; }
        public bool bFlagPrimary { get; set; }
        public string cgreet { get; set; }
        public string caddressee { get; set; }
        public string ctitle { get; set; }
        public string cBusinessName { get; set; }
        public string cstreet1 { get; set; }
        public string cstreet2 { get; set; }
        public string cstreet3 { get; set; }
        public string ccity { get; set; }
        public string cstate { get; set; }
        public string czip { get; set; }
        public string ccountry { get; set; }
        public string croute { get; set; }
        public string caddrpoint { get; set; }
    }
}
