// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetViewInvestmentDataResult
    {
        public int iKeyID { get; set; }
        public int iKeyAcct { get; set; }
        public string cAcctnum { get; set; }
        public int iKeyPrimaryClient { get; set; }
        public string cPrimaryClientName { get; set; }
        public int iKeySymbol { get; set; }
        public int iKeyFlex { get; set; }
        public int iKeyModule { get; set; }
        public int iCodeBasisType { get; set; }
        public string InvClass { get; set; }
        public string cSymbol { get; set; }
        public string cSymbolDesc { get; set; }
        public string cAlternateID { get; set; }
        public bool bFlagAcctCashBalance { get; set; }
        public DateTime? dProcessStart { get; set; }
        public string cInvTypeDesc { get; set; }
        public int iCodeNvstType { get; set; }
        [Column("nNumUnits", TypeName = "decimal(16,6)")]
        public decimal? nNumUnits { get; set; }
        public decimal? yMktVal { get; set; }
        [Column("nUnitVal", TypeName = "decimal(16,6)")]
        public decimal? nUnitVal { get; set; }
        public DateTime? dValDate { get; set; }
        public string cCusip { get; set; }
        public bool bflagfixedval { get; set; }
        public DateTime? dEffective { get; set; }
        public DateTime? dLiquidated { get; set; }
        [Column("nRORTime", TypeName = "decimal(12,4)")]
        public decimal? nRORTime { get; set; }
        [Column("nRORDollar", TypeName = "decimal(12,4)")]
        public decimal? nRORDollar { get; set; }
        public DateTime? dValuedROR { get; set; }
        public decimal? yCostBasis { get; set; }
        public decimal? yUnrealGain { get; set; }
        public decimal? yRealGain { get; set; }
        public string cInvStatusDesc { get; set; }
        public decimal? yDistributionsPaidout { get; set; }
        public decimal? yDistributionsReinvested { get; set; }
        public decimal? yCapGainLongPaidOut { get; set; }
        public decimal? yCapGainShortPaidOut { get; set; }
        public decimal? yInterestPaidOut { get; set; }
        public decimal? yDividendPaidOut { get; set; }
        public decimal? yCapGainLongReinvested { get; set; }
        public decimal? yCapGainShortReinvested { get; set; }
        public decimal? yInterestReinvested { get; set; }
        public decimal? yDividendReinvested { get; set; }
        public decimal? yInterestAccrued { get; set; }
        public bool bFlagAccrueInt { get; set; }
        public decimal? yMoneyIn { get; set; }
        public decimal? yMoneyOut { get; set; }
        public decimal? yNetTransfers { get; set; }
        public decimal? yNetExpenses { get; set; }
        public decimal? yNetAdjustments { get; set; }
        public string ObjectiveDesc { get; set; }
        public string SectorDesc { get; set; }
        public string CategoryDesc { get; set; }
        public string cCompanyDesc { get; set; }
        public int iProducer1NameKeyID { get; set; }
        public string cProducerName { get; set; }
        public decimal? yNetFees { get; set; }
        public DateTime? dprocess { get; set; }
        public int iCodeTaxStatus { get; set; }
        public DateTime? dclose { get; set; }
        public string cBasisTypeDesc { get; set; }
        public string cAcctTypeDesc { get; set; }
        public string cAcctTypeCode { get; set; }
        public bool bFlagFixedValueTaxLot { get; set; }
        public bool bFlagAccountPlaceholder { get; set; }
        public int iKeyPrimaryClientProducer { get; set; }
        public string PrimaryProducerAdvisorVaultUserName { get; set; }
        public string InvestorPrimaryProducerName { get; set; }
        public string InvestorPrimaryEmailAddress { get; set; }
        public string InvestorFirstName { get; set; }
        public string InvestorLastName { get; set; }
        public string InvestorPrimaryPhone { get; set; }
    }
}
