// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetEventSummaryByUserResult
    {
        public int? iAppts_Completed { get; set; }
        public int? iAppts_UnCompleted { get; set; }
        public int? iCalls_Completed { get; set; }
        public int? iCalls_UnCompleted { get; set; }
        public int? iTasks_Completed { get; set; }
        public int? iTasks_UnCompleted { get; set; }
        public int? iAppts_Total { get; set; }
        public int? iTasks_Total { get; set; }
        public int? iCalls_Total { get; set; }
        public int? iCompleted_Total { get; set; }
        public int? iUnCompleted_Total { get; set; }
        public int? iAppts_Older { get; set; }
        public int? iAppts_Newer { get; set; }
        public int? iTasks_Older { get; set; }
        public int? iTasks_Newer { get; set; }
        public int? iCalls_Older { get; set; }
        public int? iCalls_Newer { get; set; }
        public int? iOlder_Total { get; set; }
        public int? iNewer_Total { get; set; }
        public int? iGrand_Total { get; set; }
    }
}
