// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetPartnerListForClientResult
    {
        public int? ModuleKey { get; set; }
        public string ModuleDescription { get; set; }
        public bool? bSelected { get; set; }
        public int? ikeyAccount { get; set; }
        public string cAccount { get; set; }
    }
}
