// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetUserGroupLookupDataResult
    {
        public int iKeyID { get; set; }
        public string cUserGroupName { get; set; }
        public bool bFlagDeactivate { get; set; }
        public string Active { get; set; }
        public int? EventCount { get; set; }
    }
}
