// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetCalendarUserLookupDataResult
    {
        public int iKeyID { get; set; }
        public string cName { get; set; }
        public string cCalendarType { get; set; }
        public string cUserName { get; set; }
        public bool? bUserCalendar { get; set; }
        public bool? bUserGroupCalendar { get; set; }
        public int iUserScheduleColor { get; set; }
        public int? iTotalEvents { get; set; }
    }
}
