// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_GetWorkflowSummaryByUserGroupResult
    {
        public int? iWorkflows_Active_Created { get; set; }
        public int? iWorkflows_Active_Notify { get; set; }
        public int? iWorkflows_Completed_Created { get; set; }
        public int? iWorkflows_Completed_Notify { get; set; }
        public int? iWorkflows_Overdue_Created { get; set; }
        public int? iWorkflows_Overdue_Notify { get; set; }
        public int? iWorkflows_Terminated_Created { get; set; }
        public int? iWorkflows_Terminated_Notify { get; set; }
        public int? iWorkflowEvents_Active_Assigned { get; set; }
        public int? iWorkflowEvents_Active_Completed { get; set; }
        public int? iWorkflowEvents_Completed_Assigned { get; set; }
        public int? iWorkflowEvents_Completed_Completed { get; set; }
        public int? iWorkflowEvents_Pending_Assigned { get; set; }
        public int? iWorkflowEvents_Pending_Completed { get; set; }
        public int? iWorkflowEvents_Terminated_Assigned { get; set; }
        public int? iWorkflowEvents_Terminated_Completed { get; set; }
        public int? iWorkflowMasters_Owner { get; set; }
        public int? iWorkflowEventMasters_Default { get; set; }
    }
}
