// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_MobileGetAccountNewBizListResult
    {
        public int iKeyID { get; set; }
        public string cAction { get; set; }
        public DateTime? dInitial { get; set; }
        public DateTime? dCompleted { get; set; }
    }
}
