// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_MobileGetRecentNameListResult
    {
        public string FullName { get; set; }
        public string SortName { get; set; }
        public int UniqueNameID { get; set; }
        public string NameTypeDescPrimary { get; set; }
        public string Address1 { get; set; }
        public string CityStateZip { get; set; }
        public int iOrder { get; set; }
        public string PhoneCountryCode { get; set; }
        public string PhoneAreaCode { get; set; }
        public string PhoneNum { get; set; }
        public string NameStatus { get; set; }
        public string PrimaryProducer { get; set; }
    }
}
