// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_MobileGetAccountRelationListResult
    {
        public string RelatedName { get; set; }
        public int UniqueNameID { get; set; }
        public string Relationship { get; set; }
        public int? RelationshipOrder { get; set; }
    }
}
