// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_MobileLoginSSOResult
    {
        public int ReturnCode { get; set; }
        public int UserKeyID { get; set; }
        public int CalendarKeyID { get; set; }
        public string UserViewName { get; set; }
        public string UserInitials { get; set; }
        public string UserName { get; set; }
        public string UserID { get; set; }
        public string InsuranceModule { get; set; }
        public string InvestmentModule { get; set; }
    }
}
