// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_Mobile2GetPhoneDataResult
    {
        public int UniquePhoneID { get; set; }
        public int UniqueNameID { get; set; }
        public int UniqueHouseholdID { get; set; }
        public string PhoneType { get; set; }
        public int icodephone { get; set; }
        public string Contact { get; set; }
        public string CountryCode { get; set; }
        public string Areacode { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneExtension { get; set; }
        public string FullPhone { get; set; }
        public bool? IsPrimary { get; set; }
        public string WhoChanged { get; set; }
        public DateTime? WhenChanged { get; set; }
        public string WhoAdded { get; set; }
        public DateTime? WhenAdded { get; set; }
        public string mcomment { get; set; }
        public Guid gUid { get; set; }
        public Guid UniqueNameGUID { get; set; }
    }
}
