// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_Mobile2GetFlexNameFieldsResult
    {
        public int ikeyid { get; set; }
        [Column("nflexfld1", TypeName = "decimal(13,2)")]
        public decimal nflexfld1 { get; set; }
        [Column("nflexfld2", TypeName = "decimal(13,2)")]
        public decimal nflexfld2 { get; set; }
        [Column("nflexfld3", TypeName = "decimal(13,2)")]
        public decimal nflexfld3 { get; set; }
        [Column("nflexfld4", TypeName = "decimal(13,2)")]
        public decimal nflexfld4 { get; set; }
        [Column("nflexfld5", TypeName = "decimal(16,6)")]
        public decimal nflexfld5 { get; set; }
        [Column("nflexfld6", TypeName = "decimal(16,6)")]
        public decimal nflexfld6 { get; set; }
        public int iflexfld7 { get; set; }
        public int iflexfld8 { get; set; }
        public string cflexfld9 { get; set; }
        public string cflexfld10 { get; set; }
        public string cflexfld11 { get; set; }
        public string cflexfld12 { get; set; }
        public DateTime? dflexfld13 { get; set; }
        public DateTime? dflexfld14 { get; set; }
        public DateTime? dflexfld15 { get; set; }
        public DateTime? dflexfld16 { get; set; }
        public string cflexfld17 { get; set; }
        public string cflexfld18 { get; set; }
        public string cflexfld19 { get; set; }
        public string cflexfld20 { get; set; }
        public DateTime? dflexfld21 { get; set; }
        public DateTime? dflexfld22 { get; set; }
        public string cflexfld23 { get; set; }
        public string cflexfld24 { get; set; }
        public string cflexfld25 { get; set; }
        public string cflexfld26 { get; set; }
        public string cflexfld27 { get; set; }
        public string cflexfld28 { get; set; }
        public string cflexfld29 { get; set; }
        public string cflexfld30 { get; set; }
        public string cWhoChange { get; set; }
        public DateTime? dLastChange { get; set; }
        public string cWhoAdded { get; set; }
        public DateTime? dWhenAdded { get; set; }
        public string cSerialId { get; set; }
        public Guid gUid { get; set; }
        public int iRecVersion { get; set; }
    }
}
