// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_MobileLoginResult
    {
        public int ReturnCode { get; set; }
        public int NameCount { get; set; }
        public int UserKeyID { get; set; }
        public int UserRole { get; set; }
        public int? UserGuid { get; set; }
        public int CalendarKeyID { get; set; }
        public string UserViewName { get; set; }
        public string UserInitials { get; set; }
        public string InsuranceModule { get; set; }
        public string InvestmentModule { get; set; }
        public int DefaultAddressLocationCodeKeyID { get; set; }
        public int DefaultPhoneLocationCodeKeyID { get; set; }
        public int DefaultProducerKeyID { get; set; }
        public int DefaultAgencyKeyID { get; set; }
        public bool? ShowLiquidatedInvestments { get; set; }
        public bool? ShowTerminatedPolicies { get; set; }
        public bool? UserDisabled { get; set; }
        public bool? UserDeactivated { get; set; }
        public bool? MobileAccess { get; set; }
        public bool? MobileAccessLimited { get; set; }
        public string UserID { get; set; }
        public bool? RestrictAddressesOnePerLocation { get; set; }
        public bool? RestrictPhonesOnePerLocation { get; set; }
        public int DefaultCalendarAppointmentLength { get; set; }
        public int DefaultCalendarTaskTime { get; set; }
        public int DefaultCalendarPriority { get; set; }
        public int DefaultCalendarAppointmentColor { get; set; }
        public int DefaultCalendarTaskColor { get; set; }
        public int DefaultCalendarCallColor { get; set; }
        public int DefaultCalendarDayOfWeekStart { get; set; }
        public string CalendarName { get; set; }
        public string DatabaseVersion { get; set; }
        public bool? ShowAccountNumbers { get; set; }
    }
}
