// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_MobileGetWebDataResult
    {
        public int UniqueWebID { get; set; }
        public int UniqueNameID { get; set; }
        public string Contact { get; set; }
        public string BusinessName { get; set; }
        public string WebAddress { get; set; }
        public string Comment { get; set; }
        public bool? IsPrimary { get; set; }
        public string WhoChanged { get; set; }
        public DateTime? WhenChanged { get; set; }
        public string WhoAdded { get; set; }
        public DateTime? WhenAdded { get; set; }
        public Guid gUid { get; set; }
    }
}
