// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_Mobile2GetFileDataResult
    {
        public int iKeyID { get; set; }
        public int iKeyLink { get; set; }
        public int NameID { get; set; }
        public string ReferenceLabel { get; set; }
        public string ReferenceType { get; set; }
        public int ReferenceID { get; set; }
        public string cDescription { get; set; }
        public DateTime? dFiledate { get; set; }
        public int iFileSize { get; set; }
        public string FileCategory { get; set; }
        public string FileSource { get; set; }
        public string WhoChanged { get; set; }
        public DateTime? WhenChanged { get; set; }
        public string WhoAdded { get; set; }
        public DateTime? WhenAdded { get; set; }
        public string mFilename { get; set; }
        public int iCodeFileSource { get; set; }
        public int iCodeFileCat { get; set; }
        public string cFileLink { get; set; }
        public Guid gUid { get; set; }
        public Guid UniqueNameGUID { get; set; }
        public string ReadyDocURL { get; set; }
    }
}
