// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_Mobile2GetInvestmentTransactionsResult
    {
        public int UniqueTransactionID { get; set; }
        public DateTime? DateOfTransaction { get; set; }
        public string TransType { get; set; }
        [Column("TransShares", TypeName = "decimal(16,6)")]
        public decimal TransShares { get; set; }
        [Column("TransSharePrice", TypeName = "decimal(16,6)")]
        public decimal TransSharePrice { get; set; }
        public decimal TransPrincipal { get; set; }
        public decimal TransClientTotal { get; set; }
    }
}
