// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_Mobile2GetCalendarUserResult
    {
        public int CalendarKeyID { get; set; }
        public Guid CalendarGUID { get; set; }
        public int? UserKeyID { get; set; }
        public string Name { get; set; }
        public int DefaultCalendarAppointmentLength { get; set; }
        public int DefaultCalendarTaskTime { get; set; }
        public int DefaultCalendarPriority { get; set; }
        public int DefaultCalendarAppointmentColor { get; set; }
        public int DefaultCalendarTaskColor { get; set; }
        public int DefaultCalendarCallColor { get; set; }
        public int DefaultCalendarDayOfWeekStart { get; set; }
        public bool AppointmentsRequireName { get; set; }
        public bool RollTasks { get; set; }
    }
}
