// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_Mobile2GetSavedQuerySetResult
    {
        public int iKeyId { get; set; }
        public int iKeySavedSet { get; set; }
        public string cUniqueConditionName { get; set; }
        public string cOperator { get; set; }
        public string cValue { get; set; }
        public string cWhoChange { get; set; }
        public DateTime? dLastChange { get; set; }
        public string cWhoAdded { get; set; }
        public DateTime? dWhenAdded { get; set; }
        public Guid gUid { get; set; }
    }
}
