// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_Mobile2GetImageDataResult
    {
        public int ImageKey { get; set; }
        public Guid ImageGUID { get; set; }
        public int ClientKey { get; set; }
        public byte[] FullImage { get; set; }
        public byte[] Thumbnail { get; set; }
        public Guid ClientGUID { get; set; }
    }
}
