// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_Mobile2GetAlbridgeApplinkDataResult
    {
        public int? NameKeyID { get; set; }
        public int? AccountKeyID { get; set; }
        public int? ProducerKeyID { get; set; }
        public string AlbridgeUserID { get; set; }
        public string FinancialIntID { get; set; }
        public string TaxID { get; set; }
    }
}
