// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_MobileGetHouseholdDataResult
    {
        public int UniqueLinkedNameID { get; set; }
        public string LinkedFullName { get; set; }
        public string LinkedSortName { get; set; }
        public string LinkRelationship { get; set; }
        public string HouseholdName { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public int? AgeActual { get; set; }
        public string NameTypeDescriptionPrimary { get; set; }
        public string WhoChanged { get; set; }
        public DateTime? LastChanged { get; set; }
    }
}
