// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_Mobile2GetReportListResult
    {
        public int iKeyId { get; set; }
        public int iKeyGroup { get; set; }
        public int iKeyProgram { get; set; }
        public int iKeyFootnote { get; set; }
        public string cDescription { get; set; }
        public string mComment { get; set; }
        public string cReportname { get; set; }
        public string mReportXML { get; set; }
        public string GroupName { get; set; }
        public string ProgramName { get; set; }
        public string ProgramDesc { get; set; }
    }
}
