// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_Mobile2GetViewClientDataCountResult
    {
        public int? coverages { get; set; }
        public int? annuitycoverages { get; set; }
        public int? policies { get; set; }
        public int? annuitypolicies { get; set; }
        public int? accounts { get; set; }
        public int? annuityaccounts { get; set; }
        public int? notetopics { get; set; }
        public int? markets { get; set; }
        public int? links { get; set; }
        public int? files { get; set; }
        public int? events { get; set; }
        public int? contactnewbizes { get; set; }
        public int? newbiz { get; set; }
    }
}
