// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_Mobile2GetViewableCalendarsForGroupResult
    {
        public int CalendarKeyID { get; set; }
        public Guid CalendarGUID { get; set; }
        public string CalendarName { get; set; }
        public int UserKeyID { get; set; }
    }
}
