// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_Mobile2GetFlexLabelsResult
    {
        public int iKeyId { get; set; }
        public int iCodeType { get; set; }
        public string cflabel01 { get; set; }
        public string cflabel02 { get; set; }
        public string cflabel03 { get; set; }
        public string cflabel04 { get; set; }
        public string cflabel05 { get; set; }
        public string cflabel06 { get; set; }
        public string cflabel07 { get; set; }
        public string cflabel08 { get; set; }
        public string cflabel09 { get; set; }
        public string cflabel10 { get; set; }
        public string cflabel11 { get; set; }
        public string cflabel12 { get; set; }
        public string cflabel13 { get; set; }
        public string cflabel14 { get; set; }
        public string cflabel15 { get; set; }
        public string cflabel16 { get; set; }
        public string cflabel17 { get; set; }
        public string cflabel18 { get; set; }
        public string cflabel19 { get; set; }
        public string cflabel20 { get; set; }
        public string cflabel21 { get; set; }
        public string cflabel22 { get; set; }
        public string cflabel23 { get; set; }
        public string cflabel24 { get; set; }
        public string cflabel25 { get; set; }
        public string cflabel26 { get; set; }
        public string cflabel27 { get; set; }
        public string cflabel28 { get; set; }
        public string cflabel29 { get; set; }
        public string cflabel30 { get; set; }
        public string cChoices9 { get; set; }
        public string cChoices10 { get; set; }
        public string cChoices11 { get; set; }
        public string cChoices12 { get; set; }
        public string cChoices17 { get; set; }
        public string cChoices18 { get; set; }
        public string cChoices19 { get; set; }
        public string cChoices20 { get; set; }
        public string cChoices23 { get; set; }
        public string cChoices24 { get; set; }
        public string cChoices25 { get; set; }
        public string cChoices26 { get; set; }
        public string cChoices27 { get; set; }
        public string cChoices28 { get; set; }
        public string cChoices29 { get; set; }
        public string cChoices30 { get; set; }
        public bool bFlagReadOnly1 { get; set; }
        public bool bFlagReadOnly2 { get; set; }
        public bool bFlagReadOnly3 { get; set; }
        public bool bFlagReadOnly4 { get; set; }
        public bool bFlagReadOnly5 { get; set; }
        public bool bFlagReadOnly6 { get; set; }
        public bool bFlagReadOnly7 { get; set; }
        public bool bFlagReadOnly8 { get; set; }
        public bool bFlagReadOnly9 { get; set; }
        public bool bFlagReadOnly10 { get; set; }
        public bool bFlagReadOnly11 { get; set; }
        public bool bFlagReadOnly12 { get; set; }
        public bool bFlagReadOnly13 { get; set; }
        public bool bFlagReadOnly14 { get; set; }
        public bool bFlagReadOnly15 { get; set; }
        public bool bFlagReadOnly16 { get; set; }
        public bool bFlagReadOnly17 { get; set; }
        public bool bFlagReadOnly18 { get; set; }
        public bool bFlagReadOnly19 { get; set; }
        public bool bFlagReadOnly20 { get; set; }
        public bool bFlagReadOnly21 { get; set; }
        public bool bFlagReadOnly22 { get; set; }
        public bool bFlagReadOnly23 { get; set; }
        public bool bFlagReadOnly24 { get; set; }
        public bool bFlagReadOnly25 { get; set; }
        public bool bFlagReadOnly26 { get; set; }
        public bool bFlagReadOnly27 { get; set; }
        public bool bFlagReadOnly28 { get; set; }
        public bool bFlagReadOnly29 { get; set; }
        public bool bFlagReadOnly30 { get; set; }
        public string cWhoChange { get; set; }
        public DateTime? dLastChange { get; set; }
        public string cWhoAdded { get; set; }
        public DateTime? dWhenAdded { get; set; }
        public string cSerialId { get; set; }
        public Guid gUid { get; set; }
        public int iRecVersion { get; set; }
        public string ClientTypeString { get; set; }
    }
}
