// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_Mobile2LoginResult
    {
        public int ReturnCode { get; set; }
        public int NameCount { get; set; }
        public int UserKeyID { get; set; }
        public int UserRole { get; set; }
        public int? UserGuid { get; set; }
        public int CalendarKeyID { get; set; }
        public string UserViewName { get; set; }
        public int UserViewKeyID { get; set; }
        public string UserInitials { get; set; }
        public string InsuranceModule { get; set; }
        public string InvestmentModule { get; set; }
        public int DefaultAddressLocationCodeKeyID { get; set; }
        public int DefaultPhoneLocationCodeKeyID { get; set; }
        public int DefaultProducerKeyID { get; set; }
        public int DefaultAgencyKeyID { get; set; }
        public bool? ShowLiquidatedInvestments { get; set; }
        public bool? ShowTerminatedPolicies { get; set; }
        public bool? UserDisabled { get; set; }
        public bool? UserDeactivated { get; set; }
        public bool? MobileAccess { get; set; }
        public bool? MobileAccessLimited { get; set; }
        public bool? PartialAlphabetLookup { get; set; }
        public string UserID { get; set; }
        public string MobileCulture { get; set; }
        public bool? RestrictAddressesOnePerLocation { get; set; }
        public bool? RestrictPhonesOnePerLocation { get; set; }
        public int DefaultCalendarAppointmentLength { get; set; }
        public int DefaultCalendarTaskTime { get; set; }
        public int DefaultCalendarPriority { get; set; }
        public int DefaultCalendarAppointmentColor { get; set; }
        public int DefaultCalendarTaskColor { get; set; }
        public int DefaultCalendarCallColor { get; set; }
        public int DefaultCalendarDayOfWeekStart { get; set; }
        public string CalendarName { get; set; }
        public string DatabaseVersion { get; set; }
        public bool? ShowAccountNumbers { get; set; }
        public bool? ShowAnnuityPoliciesOnViewClientWithInsurance { get; set; }
        public bool? ShowAnnuityPoliciesOnViewClientWithAnnuities { get; set; }
        public bool? ShowAnnuityAccountsOnViewClientWithInvestments { get; set; }
        public bool? ShowAnnuityAccountsOnViewClientWithAnnuities { get; set; }
        public int? FormAutomationOption { get; set; }
        public string LaserAppAnywhereUserID { get; set; }
        public string LaserAppAnywherePasswordEncrypted { get; set; }
        public int? MaxRecentNames { get; set; }
        public bool? ForcePasswordChange { get; set; }
        public bool? PreventPasswordChange { get; set; }
        public bool? ShowCustodianContactInfoOnReports { get; set; }
        public bool? ShowSocialMedia { get; set; }
        public int MustChangePasswordDays { get; set; }
        public int CannotChangePasswordDays { get; set; }
        public int CannotRepeatPasswords { get; set; }
        public int LockoutAttempts { get; set; }
        public int? PreviousPasswordsXML { get; set; }
        public int? LastPasswordChange { get; set; }
        public int RecreateUserViews { get; set; }
        public string Email { get; set; }
        public int RollTasks { get; set; }
        public int MFAEnabled { get; set; }
        public int MFAFreq { get; set; }
    }
}
