// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_Mobile2GetCalendarResult
    {
        public string cdescription { get; set; }
        public int DetailKeyID { get; set; }
        public int iKeyEvent { get; set; }
        public DateTime? dBegin { get; set; }
        public DateTime? dEnd { get; set; }
        public DateTime? dDue { get; set; }
        public DateTime? dJustDate { get; set; }
        public bool bFlagCompleted { get; set; }
    }
}
