// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_Mobile2MoneyGuidProByNameResult
    {
        public int iKeyID { get; set; }
        public string cFirstname { get; set; }
        public string cMiddle { get; set; }
        public string cLastname { get; set; }
        public DateTime? dDOB { get; set; }
        public int iCodeGender { get; set; }
        public string cStreet1 { get; set; }
        public string cStreet2 { get; set; }
        public string cStreet3 { get; set; }
        public string cCity { get; set; }
        public string cState { get; set; }
        public string cZip { get; set; }
        public string cFullPhone { get; set; }
        public string cEmail { get; set; }
        public bool bFlagHeadOfHouse { get; set; }
        public int iKeyPrimaryHousehold { get; set; }
        public Guid guid { get; set; }
        public int iKeyProducerName { get; set; }
        public string cMoneyGuideProInstitutionID { get; set; }
        public string cMoneyGuideProVirtualDirectory { get; set; }
        public Guid producerGuid { get; set; }
        public string cProducerLastname { get; set; }
        public string cProducerFirstname { get; set; }
        public string cProducerMiddlename { get; set; }
        public string cProducerAddressStreet1 { get; set; }
        public string cProducerAddressStreet2 { get; set; }
        public string cProducerAddressStreet3 { get; set; }
        public string cProducerAddressCity { get; set; }
        public string cProducerAddressState { get; set; }
        public string cProducerAddressZip { get; set; }
        public string cProducerPhone { get; set; }
        public string cProducerEmail { get; set; }
        public int iCodeMaritalStatus { get; set; }
        public bool? bFlagOrganization { get; set; }
        public int iKeyPdcr { get; set; }
        public int iKeySpouse { get; set; }
        public int? iKeyHouseoldThatThisNameIsHeadOf { get; set; }
    }
}
