// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_NoteCatalogValidateResult
    {
        [Column("configuration name")]
        public string configurationname { get; set; }
        [Column("is deprecated")]
        public string isdeprecated { get; set; }
        [Column("configuration value type")]
        public string configurationvaluetype { get; set; }
        public long? minimum { get; set; }
        public long? maximum { get; set; }
    }
}
