// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_TransactionRegistrationExportResult
    {
        [Column("Investor Sort Name")]
        public string InvestorSortName { get; set; }
        [Column("Account Number")]
        public string AccountNumber { get; set; }
        [Column("Account Type")]
        public string AccountType { get; set; }
        public string Registration { get; set; }
        [Column("Download Source")]
        public string DownloadSource { get; set; }
        public string AccountCustodian { get; set; }
        [Column("Asset Description")]
        public string AssetDescription { get; set; }
        public string Symbol { get; set; }
        public string CUSIP { get; set; }
        [Column("CUSIP Ext")]
        public string CUSIPExt { get; set; }
        [Column("Trade Date")]
        public DateTime? TradeDate { get; set; }
        [Column("Settle Date")]
        public DateTime? SettleDate { get; set; }
        [Column("Transaction Type")]
        public string TransactionType { get; set; }
        [Column("Shares", TypeName = "decimal(16,6)")]
        public decimal Shares { get; set; }
        [Column("Price", TypeName = "decimal(16,6)")]
        public decimal Price { get; set; }
        [Column("Transaction Total")]
        public decimal TransactionTotal { get; set; }
    }
}
