// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models
{
    public partial class sp_ValidateUsernamePasswordResult
    {
        public int iKeyId { get; set; }
        public string cRecordType { get; set; }
        public string cUserInitials { get; set; }
        public string cUserID { get; set; }
        public string cName { get; set; }
        public bool bFlagLoggedIn { get; set; }
        public DateTime? dLastLogin { get; set; }
        public int iKeyDefaultView { get; set; }
        public int iKeyCurrentView { get; set; }
        public int? iLoggedIn { get; set; }
        public int iKeyCalendar { get; set; }
        public int iFailedLogin { get; set; }
        public DateTime? dLastPasswordChange { get; set; }
        public bool bFlagDisable { get; set; }
        public bool bFlagDeactivate { get; set; }
        public bool bFlagForcePasswordChange { get; set; }
        public string cRoleName { get; set; }
        public int iKeyRole { get; set; }
        public int iKeyName { get; set; }
        public string cStationName { get; set; }
        public bool bFlagPreventPasswordChange { get; set; }
        public Guid gUid { get; set; }
    }
}
