// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwAppAutomationDataByName
{
    public int UniqueNameId { get; set; }

    public string FullName { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string MiddleInitial { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public int? AgeActual { get; set; }

    public int? AgeNearest { get; set; }

    public int DependentsNumber { get; set; }

    public string DependentStatus { get; set; }

    public decimal IncomeEarned { get; set; }

    public decimal IncomeTotal { get; set; }

    public decimal NetWorth { get; set; }

    public string Gender { get; set; }

    public string Industry { get; set; }

    public string MaritalStatus { get; set; }

    public string Tobacco { get; set; }

    public string Occupation { get; set; }

    public DateTime? DateOfMarriage { get; set; }

    public string SpouseFullName { get; set; }

    public string SpouseFirstName { get; set; }

    public string SpouseMiddleName { get; set; }

    public string SpouseLastName { get; set; }

    public string SpouseMiddleInitial { get; set; }

    public DateTime? SpouseDateOfBirth { get; set; }

    public int? SpouseAgeActual { get; set; }

    public int? SpouseAgeNearest { get; set; }

    public string AddressLocation { get; set; }

    public string Greeting { get; set; }

    public string Addressee { get; set; }

    public string JobTitle { get; set; }

    public string Company { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string Address3 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string ZipCode { get; set; }

    public string Region { get; set; }

    public string Country { get; set; }

    public string CarrierRoute { get; set; }

    public string DeliveryPoint { get; set; }

    public string PhoneLocation { get; set; }

    public string PhoneContact { get; set; }

    public string PhoneCountryCode { get; set; }

    public string PhoneAreaCode { get; set; }

    public string PhoneNumber { get; set; }

    public string PhoneExtension { get; set; }

    public string FullPhone { get; set; }

    public string FaxLocation { get; set; }

    public string FaxContact { get; set; }

    public string FaxCountryCode { get; set; }

    public string FaxAreacode { get; set; }

    public string FaxNumber { get; set; }

    public string FaxExtension { get; set; }

    public string FullFax { get; set; }
}