// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwDlfregistration
{
    public int IKeyFile { get; set; }

    public string CFilename { get; set; }

    public DateTime? DProcessed { get; set; }

    public string CProcessResultAbbr { get; set; }

    public string CProcessResultDesc { get; set; }

    public string CRegistration { get; set; }

    public int ICodeProcessResult { get; set; }

    public string CAccountNumber { get; set; }

    public DateTime? DAcquiredAccount { get; set; }

    public DateTime? DAcquiredInvestment { get; set; }

    public string CAccountObjectiveCode { get; set; }

    public string CAccountObjectiveDescription { get; set; }

    public string CAccountTypeCode { get; set; }

    public string CAccountTypeDescription { get; set; }

    public string CRep1Code { get; set; }

    public string CRep1Fullname { get; set; }

    public string CSymbol { get; set; }

    public string CDescription { get; set; }

    public string CCusip { get; set; }

    public string CCusipExt { get; set; }

    public string CAlternateId { get; set; }

    public string CSecurityId { get; set; }

    public string CSecurityName { get; set; }

    public string CCompanyCode { get; set; }

    public string CCompanyDescription { get; set; }

    public string CCategoryCode { get; set; }

    public string CCategoryDescription { get; set; }

    public string CSectorCode { get; set; }

    public string CSectorDescription { get; set; }

    public string CInvTypeCode { get; set; }

    public string CInvTypeDescription { get; set; }

    public bool? BFlagFixedValue { get; set; }

    public bool? BFlagMoneyMarket { get; set; }

    public decimal YContributions { get; set; }

    public decimal YCostBasis { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CAaproducer1Name { get; set; }

    public string CReportMessage { get; set; }

    public string InvestorFullName { get; set; }

    public string InvestorSortName { get; set; }
}