// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwDlfpolicyCoverage
{
    public Guid Guid { get; set; }

    public int IKeyFile { get; set; }

    public string CFilename { get; set; }

    public DateTime? DProcessed { get; set; }

    public string CProcessResultAbbrPolicy { get; set; }

    public string CProcessResultDescPolicy { get; set; }

    public int ICodeProcessResultPolicy { get; set; }

    public string CProcessResultAbbrCoverage { get; set; }

    public string CProcessResultDescCoverage { get; set; }

    public int ICodeProcessResultCoverage { get; set; }

    public string CPolicyNumber { get; set; }

    public DateTime? DEffective { get; set; }

    public string CRegistration { get; set; }

    public string CRep1Code { get; set; }

    public string CRep1Fullname { get; set; }

    public string CPlanAbbreviation { get; set; }

    public string CPlanDescription { get; set; }

    public string CCompanyCode { get; set; }

    public string CCompanyDescription { get; set; }

    public string ClassDescription { get; set; }

    public string CPlanTypeCode { get; set; }

    public string CPlanTypeDescription { get; set; }

    public decimal YBenefitAmount { get; set; }

    public decimal? YCashValue { get; set; }

    public decimal? YPremiumToDate { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CAaproducer1Name { get; set; }

    public string CReportMessagePolicy { get; set; }

    public string CReportMessageCoverage { get; set; }

    public string OwnerFullName { get; set; }

    public string OwnerSortName { get; set; }
}