// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwDlfbalance
{
    public int IKeyFile { get; set; }

    public string CFilename { get; set; }

    public DateTime? DProcessed { get; set; }

    public string CProcessResultAbbr { get; set; }

    public string CProcessResultDesc { get; set; }

    public int ICodeProcessResult { get; set; }

    public string CAccountNumber { get; set; }

    public string CAccountTypeCode { get; set; }

    public string CAccountTypeDescription { get; set; }

    public string CCompanyCode { get; set; }

    public string CCompanyDescription { get; set; }

    public DateTime? DBalanceDate { get; set; }

    public decimal? YCashBalance { get; set; }

    public decimal? YCashAvailable { get; set; }

    public decimal? YEquity { get; set; }

    public decimal? YMarketValue { get; set; }

    public decimal? YBuyingPower { get; set; }

    public decimal? YMarketValueShort { get; set; }

    public decimal? YMarketValueLong { get; set; }

    public decimal? YMarginBalance { get; set; }

    public decimal? YMarginMarketValue { get; set; }

    public decimal? YSmabalance { get; set; }

    public decimal? YMoneyMarketBalance { get; set; }

    public string COfficeNumber { get; set; }

    public string CRep1Code { get; set; }

    public string CRep1Fullname { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CAaproducer1Name { get; set; }

    public string CReportMessage { get; set; }

    public string InvestorFullName { get; set; }

    public string InvestorSortName { get; set; }
}