// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwDlfpolicyPosition
{
    public int IKeyFile { get; set; }

    public string CFilename { get; set; }

    public DateTime? DProcessed { get; set; }

    public string CProcessResultAbbr { get; set; }

    public string CProcessResultDesc { get; set; }

    public int ICodeProcessResult { get; set; }

    public string CPolicyNumber { get; set; }

    public DateTime? DPosition { get; set; }

    public DateTime? DPremiumPaidThru { get; set; }

    public string CRep1Code { get; set; }

    public string CRep1Fullname { get; set; }

    public string CPlanAbbreviation { get; set; }

    public string CPlanDescription { get; set; }

    public string CCompanyCode { get; set; }

    public string CCompanyDescription { get; set; }

    public string ClassDescription { get; set; }

    public string CPlanTypeCode { get; set; }

    public string CPlanTypeDescription { get; set; }

    public decimal YCashValue { get; set; }

    public decimal YPremiumToDate { get; set; }

    public decimal YSurrenderCharge { get; set; }

    public decimal YSurrenderValue { get; set; }

    public decimal YLoanAmount { get; set; }

    public decimal YMaxAvailableLoan { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CAaproducer1Name { get; set; }

    public string CReportMessage { get; set; }

    public string OwnerFullName { get; set; }

    public string OwnerSortName { get; set; }
}