// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwDlftransaction
{
    public int IKeyFile { get; set; }

    public string CFilename { get; set; }

    public DateTime? DProcessed { get; set; }

    public string CProcessResultAbbr { get; set; }

    public string CProcessResultDesc { get; set; }

    public int ICodeProcessResult { get; set; }

    public string CAccountNumber { get; set; }

    public string CSymbol { get; set; }

    public string CDescription { get; set; }

    public string CCusip { get; set; }

    public string CCusipExt { get; set; }

    public string CAlternateId { get; set; }

    public string CSecurityId { get; set; }

    public string CSecurityName { get; set; }

    public string CCompanyCode { get; set; }

    public string CCompanyDescription { get; set; }

    public string CKey1 { get; set; }

    public string CKey2 { get; set; }

    public string CRelatedKey { get; set; }

    public DateTime? DTranDate { get; set; }

    public DateTime? DSettle { get; set; }

    public DateTime? DTransmittal { get; set; }

    public string CSourceTranTypePrimary { get; set; }

    public string CSourceTranTypeSecondary { get; set; }

    public string CTranDescription { get; set; }

    public string MTranComment { get; set; }

    public decimal NTransactionUnitCost { get; set; }

    public decimal NUnitValue { get; set; }

    public decimal NUnits { get; set; }

    public short IShareBalanceFlow { get; set; }

    public decimal YTotalPrincipal { get; set; }

    public decimal YTotalNet { get; set; }

    public decimal YCommissions { get; set; }

    public decimal YFees { get; set; }

    public decimal YWithheld { get; set; }

    public decimal YAccruedInterest { get; set; }

    public string COfficeNumber { get; set; }

    public string CRep1Code { get; set; }

    public string CRep1Fullname { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CAatransactionCodeAbbr { get; set; }

    public string CAatransactionCodeDesc { get; set; }

    public string CAaproducer1Name { get; set; }

    public string CReportMessage { get; set; }

    public string InvestorFullName { get; set; }

    public string InvestorSortName { get; set; }

    public bool BFlagUnknownTransactionType { get; set; }
}