// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwDstsecurity
{
    public int IKeyId { get; set; }

    public string CCusip { get; set; }

    public string CManagementCode { get; set; }

    public string CFundname { get; set; }

    public string CManagementCompany { get; set; }

    public string CFundcode { get; set; }

    public string CSystemId { get; set; }

    public string CSymbol { get; set; }

    public string CSecurityType { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public int IRecVersion { get; set; }

    public Guid GUid { get; set; }
}