// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwInsuranceCommissionTransactionSummary
{
    public int UniquePolicyId { get; set; }

    public int UniqueBaseCoverageId { get; set; }

    public int UniqueCoverageId { get; set; }

    public int UniqueTransactionId { get; set; }

    public int UniqueAdjustmentId { get; set; }

    public int UniqueRateTableSetId { get; set; }

    public Guid? UniqueBatchGuid { get; set; }

    public int UniqueCompanyId { get; set; }

    public int UniqueCoverageTypeId { get; set; }

    public int UniqueAgencyId { get; set; }

    public string AgencyName { get; set; }

    public string PolicyCompanyAbbr { get; set; }

    public int PolicyProducer1UniqueId { get; set; }

    public string PolicyProducer1 { get; set; }

    public int PolicyProducer2UniqueId { get; set; }

    public int PolicyProducer3UniqueId { get; set; }

    public int PolicyProducer4UniqueId { get; set; }

    public int PolicyManager1UniqueId { get; set; }

    public int PolicyManager2UniqueId { get; set; }

    public int PolicyManager3UniqueId { get; set; }

    public int PolicyManager4UniqueId { get; set; }

    public string PolicyNumber { get; set; }

    public string CoveragePlan { get; set; }

    public string TransStatusDescription { get; set; }

    public int UniqueStatusId { get; set; }

    public int Status { get; set; }

    public DateTime? DueDate { get; set; }

    public string Comment { get; set; }

    public int CoverageYear { get; set; }

    public string FirstRenewal { get; set; }

    public int PremiumYear { get; set; }

    public decimal? AgencyGrossDue { get; set; }

    public decimal AgencyGrossPaid { get; set; }

    public decimal? AgencyDistributionsDue { get; set; }

    public decimal AgencyDistributionsPaid { get; set; }

    public decimal? AgencyNetDue { get; set; }

    public decimal AgencyNetPaid { get; set; }

    public decimal? ProducersGrossDue { get; set; }

    public decimal ProducersGrossPaid { get; set; }

    public decimal? ProducersDirectDue { get; set; }

    public decimal ProducersDirectPaid { get; set; }

    public decimal? ManagersGrossDue { get; set; }

    public decimal ManagersGrossPaid { get; set; }

    public decimal? ManagersDirectDue { get; set; }

    public decimal ManagersDirectPaid { get; set; }

    public decimal? TotalDirectDue { get; set; }

    public decimal? TotalDirectPaid { get; set; }

    public DateTime? PaidDateMin { get; set; }

    public DateTime? PaidDateMax { get; set; }

    public string RateTableSetName { get; set; }

    public string PolicyOwnerSortName { get; set; }

    public int PolicyOwnerUniqueId { get; set; }

    public string CoveragePrimaryInsuredSortName { get; set; }

    public int CoveragePrimaryInsuredUniqueId { get; set; }

    public int UniquePrimaryProducerId { get; set; }

    public bool BFlagContainsBasePremium { get; set; }

    public bool BFlagContainsExcess1Premium { get; set; }

    public bool BFlagContainsExcess2Premium { get; set; }

    public bool BFlagContainsNormal { get; set; }

    public bool BFlagContainsOverride1 { get; set; }

    public bool BFlagContainsOverride2 { get; set; }

    public bool BFlagContainsParticipant { get; set; }

    public bool BFlagContainsTrailer { get; set; }

    public bool BFlagContainsFixedAmount { get; set; }

    public bool BFlagContainsAdjustment { get; set; }

    public bool BFlagContainsChargeback { get; set; }

    public string NormalTrailer { get; set; }
}