// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwMobileClient
{
    public int UniqueNameId { get; set; }

    public string FullNickName { get; set; }

    public string FullName { get; set; }

    public string SortName { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string MiddleInitial { get; set; }

    public string LastName { get; set; }

    public string NickName { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public string TaxId { get; set; }

    public string DriversLicenseId { get; set; }

    public DateTime? DlexpirationDate { get; set; }

    public DateTime? DlissueDate { get; set; }

    public int? AgeActual { get; set; }

    public int? AgeNearest { get; set; }

    public string MonthDayOfBirth { get; set; }

    public int? MonthDayDobsort { get; set; }

    public bool? OrganizationYn { get; set; }

    public string Gender { get; set; }

    public string NameStatus { get; set; }

    public string NameTypeDescPrimary { get; set; }

    public string NameTypeAbbrPrimary { get; set; }

    public int? UniqueNameTypeCodeId { get; set; }

    public string Occupation { get; set; }

    public string Greeting { get; set; }

    public string Addressee { get; set; }

    public string AddressTitle { get; set; }

    public string BusinessName { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string Address3 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string ZipPostalCode { get; set; }

    public string County { get; set; }

    public string Country { get; set; }

    public string CarrierRoute { get; set; }

    public string DeliveryPoint { get; set; }

    public string CityStateZip { get; set; }
}