// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwNameFilter10000034
{
    public int Ikeyid { get; set; }

    public int Ikeypdcr { get; set; }

    public int Ikeyoffice { get; set; }

    public int IkeyVendor { get; set; }

    public int IkeyTop { get; set; }

    public int Ikeyspouse { get; set; }

    public int IKeyNameType { get; set; }

    public int IKeyAddress { get; set; }

    public int IKeyPhone { get; set; }

    public int IKeyEmail { get; set; }

    public int IKeyUrl { get; set; }

    public int IKeyFlex { get; set; }

    public int IKeyPrimaryHouseHold { get; set; }

    public int IKeyFax { get; set; }

    public int IKeyMailingList { get; set; }

    public int IKeyPrimaryImage { get; set; }

    public int IKeyImportantInfoNote { get; set; }

    public string Cnameid { get; set; }

    public string Ctaxid { get; set; }

    public string CtaxidLookup { get; set; }

    public string Cfirstname { get; set; }

    public string Cmiddle { get; set; }

    public string Clastname { get; set; }

    public string Cnickname { get; set; }

    public string Csortname { get; set; }

    public bool Bflagpdcr { get; set; }

    public DateTime? Ddob { get; set; }

    public int? IBirthday { get; set; }

    public int ICodeGender { get; set; }

    public int ICodePhase { get; set; }

    public bool? BFlagOrganization { get; set; }

    public bool BFlagAccountPlaceholder { get; set; }

    public int ICodeTobacco { get; set; }

    public bool Bflagheadofhouse { get; set; }

    public bool Bflagphone { get; set; }

    public bool Bflagmail { get; set; }

    public bool Bflagemail { get; set; }

    public int Icodeoccupation { get; set; }

    public int ICodeIndustry { get; set; }

    public int Icodestatus { get; set; }

    public int Inumofdeps { get; set; }

    public string CDependantStatus { get; set; }

    public DateTime? Dmarried { get; set; }

    public int? IAnniversary { get; set; }

    public int ICodeMaritalStatus { get; set; }

    public string CCitizen { get; set; }

    public string CPassport { get; set; }

    public DateTime? DPassportExpiration { get; set; }

    public DateTime? DPassportIssue { get; set; }

    public int ICodeResidency { get; set; }

    public string CGreencard { get; set; }

    public DateTime? DGreencardExpiration { get; set; }

    public DateTime? DGreencardIssue { get; set; }

    public string CdriversLicense { get; set; }

    public int ICodeDriversLicenseState { get; set; }

    public DateTime? DDriversLicenseExpiration { get; set; }

    public DateTime? DDriversLicenseIssue { get; set; }

    public DateTime? DPatriotForm { get; set; }

    public decimal Yearnedinc { get; set; }

    public decimal Ytotalincome { get; set; }

    public decimal Ynetworth { get; set; }

    public decimal YMarketVal { get; set; }

    public string Cdwlid { get; set; }

    public int ICodeRecordCreationSource { get; set; }

    public string CPrefix { get; set; }

    public string CSuffix { get; set; }

    public decimal NTaxBracket { get; set; }

    public string CMedicare { get; set; }

    public string CApikey1 { get; set; }

    public string CApikey2 { get; set; }

    public string CApikey3 { get; set; }

    public int IKeyProducerReference { get; set; }

    public string CFacebook { get; set; }

    public string CLinkedIn { get; set; }

    public string CTwitter { get; set; }

    public string CGooglePlus { get; set; }

    public string CRiskAlyzeRiskNumber { get; set; }

    public int IRiskAlyzeId { get; set; }

    public DateTime? DLastSignificantChangeUtc { get; set; }

    public string CWhoChange { get; set; }

    public DateTime? DLastChange { get; set; }

    public string CWhoAdded { get; set; }

    public DateTime? DWhenAdded { get; set; }

    public string CSerialId { get; set; }

    public Guid GUid { get; set; }

    public int IRecVersion { get; set; }
}