// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwPlanningExportInvestment
{
    public int UniqueNameId { get; set; }

    public Guid NameGuid { get; set; }

    public Guid AccountGuid { get; set; }

    public Guid AssetGuid { get; set; }

    public string AccountTypeAbbreviation { get; set; }

    public string AccountTypeDescription { get; set; }

    public string AccountNumber { get; set; }

    public string AccountTitle { get; set; }

    public DateTime? AccountOpenDate { get; set; }

    public DateTime? AccountCloseDate { get; set; }

    public decimal AccountBasis { get; set; }

    public decimal AccountNetCashFlow { get; set; }

    public decimal AccountMarketValue { get; set; }

    public string SecurityCompanyAbbreviation { get; set; }

    public string SecurityCompanyDescription { get; set; }

    public string AssetName { get; set; }

    public string AssetSymbol { get; set; }

    public string AssetCusip { get; set; }

    public string AssetAlternateId { get; set; }

    public decimal AssetBasis { get; set; }

    public string SecurityTypeAbbreviation { get; set; }

    public string SecurityTypeDescription { get; set; }

    public string SecurityCategoryAbbreviation { get; set; }

    public string SecurityCategoryDescription { get; set; }

    public string AccountObjectiveAbbreviation { get; set; }

    public string AccountObjectiveDescription { get; set; }

    public string SecuritySectorAbbreviation { get; set; }

    public string SecuritySectorDescription { get; set; }

    public DateTime? AssetAcquiredDate { get; set; }

    public DateTime? AssetLiquidationDate { get; set; }

    public decimal AssetMarketValue { get; set; }

    public DateTime? AssetSharePriceDate { get; set; }

    public decimal AssetShares { get; set; }

    public decimal SharePrice { get; set; }

    public int? PolicyFundingOptionCodeId { get; set; }

    public decimal? PolicyNetBenefit { get; set; }
}