// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportInsuranceRelatedName
{
    public int UniqueNameId { get; set; }

    public int UniquePolicyId { get; set; }

    public int UniqueCoverageId { get; set; }

    public int UniquePrimaryInsuredNameId { get; set; }

    public int UniquePrimaryBeneficiaryNameId { get; set; }

    public string OwnerFullName { get; set; }

    public string RelationshipDescription { get; set; }

    public string RelatedNameType { get; set; }

    public string RelatedFullName { get; set; }

    public string RelatedSortName { get; set; }

    public int UniqueRelatedNameId { get; set; }

    public string BeneficiaryFreeForm { get; set; }
}