// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportWorkFlowMaster
{
    public int UniqueWorkflowMasterId { get; set; }

    public string Wfmdescription { get; set; }

    public int Wfmduration { get; set; }

    public int WfmeventCount { get; set; }

    public string Wfmtype { get; set; }

    public string WfmcreatorUserInitials { get; set; }

    public string WfmcreatorUserName { get; set; }

    public string FieldLabel01 { get; set; }

    public string FieldLabel02 { get; set; }

    public string FieldLabel03 { get; set; }

    public string FieldLabel04 { get; set; }

    public string FieldLabel05 { get; set; }

    public string FieldLabel06 { get; set; }
}