// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportHouseholdOf
{
    public int UniqueHouseholdHeadNameId { get; set; }

    public int UniqueMemberNameId { get; set; }

    public int UniqueHouseholdId { get; set; }

    public string HouseholdName { get; set; }

    public string HouseholdHeadFullname { get; set; }
}