// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportInvestmentTrailerComm
{
    public int? UniqueSecurityId { get; set; }

    public int? UniqueCompanyId { get; set; }

    public int UniqueInvestmentId { get; set; }

    public int? UniqueCustodianId { get; set; }

    public int UniqueAccountId { get; set; }

    public int? UniqueNameId { get; set; }

    public int? UniqueInvestorId { get; set; }

    public int? InvesorPrimaryProducerId { get; set; }

    public int? InvestorPrimaryProducerNameId { get; set; }

    public int? UniqueDlid { get; set; }

    public string InvestorFullName { get; set; }

    public string InvestorSortName { get; set; }

    public string InvestorPrimaryProducer { get; set; }

    public string InvestorHouseholdName { get; set; }

    public int? InvestorHouseholdId { get; set; }

    public string AccountNumber { get; set; }

    public string AccountTitle { get; set; }

    public string AccountTypeAndNumber { get; set; }

    public string AssetName { get; set; }

    public string AssetSymbol { get; set; }

    public string AssetCusip { get; set; }

    public string AssetCusipextension { get; set; }

    public string AssetType { get; set; }

    public string AssetCompany { get; set; }

    public string AssetCategory { get; set; }

    public string AssetCompanyAbbr { get; set; }

    public string AssetDownloadSource { get; set; }

    public decimal? AssetMarketValue { get; set; }

    public decimal? AssetShares { get; set; }

    public decimal? AssetSharePrice { get; set; }

    public DateTime? AssetSharePriceDate { get; set; }

    public DateTime? AssetAcquiredDate { get; set; }

    public DateTime? AssetLiquidatedDate { get; set; }

    public bool? BFlagTrailerCommission { get; set; }

    public decimal? TrailerCommPct { get; set; }

    public short? TrailerTimesPerYear { get; set; }

    public decimal? TrailerCommissionAmount { get; set; }

    public int? TrailerBeginsNmonthsAfterAcquired { get; set; }

    public string TrailerBeginDate { get; set; }

    public DateTime? TrailerCommsPaidThru { get; set; }

    public string AccountProducer1 { get; set; }

    public string AccountProducer2 { get; set; }

    public string AccountManager1 { get; set; }

    public int? UniqueProducer1Id { get; set; }

    public int? UniqueProducer2Id { get; set; }

    public int? UniqueManager1Id { get; set; }

    public string TrailerCalcMethod { get; set; }

    public string TrailerCalcBeginDate { get; set; }

    public string TrailerCalcEndDate { get; set; }
}