// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportNameFile
{
    public int UniqueNameId { get; set; }

    public string Description { get; set; }

    public string Filename { get; set; }

    public string Category { get; set; }
}