// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportLink
{
    public int UniqueNameId { get; set; }

    public int UniqueLinkedNameId { get; set; }

    public string LinkedFullName { get; set; }

    public string LinkedSortName { get; set; }

    public string LinkRelationship { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public int? AgeActual { get; set; }

    public string NameTypeDescriptionPrimary { get; set; }

    public string WhoChanged { get; set; }

    public DateTime? LastChanged { get; set; }
}