// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportWorkFlow
{
    public int UniqueWorkflowId { get; set; }

    public string Wfdescription { get; set; }

    public string ClientSortName { get; set; }

    public string Wfreference { get; set; }

    public int Wfduration { get; set; }

    public int Wfpriority { get; set; }

    public int WfeventCount { get; set; }

    public DateTime? WfbeginDate { get; set; }

    public DateTime? WfendDate { get; set; }

    public string Wftype { get; set; }

    public int Wfstatus { get; set; }

    public string WfcreatedByUserInitials { get; set; }

    public string WfcreatedByUserName { get; set; }

    public decimal? WfcompletedPct { get; set; }

    public decimal WftotalRevenue { get; set; }

    public string WfwhoChange { get; set; }

    public DateTime? WfchangeDate { get; set; }

    public int UniqueNameId { get; set; }

    public int UniqueAccountId { get; set; }

    public int UniquePolicyId { get; set; }

    public int UniquePrimaryProducerId { get; set; }

    public int UniqueWorkflowMasterId { get; set; }

    public int UniqueProducerGroupId { get; set; }

    public string FieldLabel01 { get; set; }

    public string FieldLabel02 { get; set; }

    public string FieldLabel03 { get; set; }

    public string FieldLabel04 { get; set; }

    public string FieldLabel05 { get; set; }

    public string FieldLabel06 { get; set; }

    public decimal? FlexField01Numeric { get; set; }

    public decimal? FlexField02Numeric { get; set; }

    public string FlexField03Text { get; set; }

    public string FlexField04Text { get; set; }

    public DateTime? FlexField05Date { get; set; }

    public DateTime? FlexField06Date { get; set; }

    public string PhaseLabel { get; set; }
}