// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportInsured
{
    public int? UniqueNameId { get; set; }

    public int? UniquePolicyId { get; set; }

    public int UniqueCoverageId { get; set; }

    public int? UniqueInsuredId { get; set; }

    public string CoverageInsuredFullName { get; set; }

    public string CoverageInsuredLastName { get; set; }

    public string CoverageInsuredFirstName { get; set; }

    public bool? CoverageIsPrimaryInsured { get; set; }

    public DateTime? CoverageInsuredEffectiveDate { get; set; }

    public int? CoverageIssueAge { get; set; }

    public DateTime? CoverageExpiration { get; set; }
}