// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportInvestmentNewBiz
{
    public int UniqueNewBizId { get; set; }

    public int UniqueNameId { get; set; }

    public string InvestorFullname { get; set; }

    public string InvestorSortName { get; set; }

    public int UniqueAccountId { get; set; }

    public string ActionComment { get; set; }

    public string ActionPriority { get; set; }

    public DateTime? ActionInitiatedDate { get; set; }

    public DateTime? ActionCompletedDate { get; set; }

    public bool? ActionCompletedYn { get; set; }

    public string VendorFullName { get; set; }

    public DateTime? ActionFollowupDate { get; set; }

    public string AccountNumber { get; set; }

    public string AccountType { get; set; }

    public string Action { get; set; }

    public string ActionCodeAbbr { get; set; }

    public string ActionCodeDescription { get; set; }

    public string ActionLastChangedBy { get; set; }

    public string ActionInitiatedBy { get; set; }

    public decimal Amount { get; set; }
}