// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportInsuranceProduction
{
    public int UniqueId { get; set; }

    public int? UniquePolicyId { get; set; }

    public int UniqueCoverageId { get; set; }

    public int? UniqueNameId { get; set; }

    public string ProducerName { get; set; }

    public int? UniqueProducerNameId { get; set; }

    public decimal? Producer1stYrSplit { get; set; }

    public decimal? ProducerRenewalSplit { get; set; }

    public decimal? ProducerCommCoverage1stYr { get; set; }

    public decimal? ProducerCommPolicy1stYr { get; set; }

    public int ProducerRank { get; set; }

    public string ProducerRankDescription { get; set; }

    public string PolicyPayor { get; set; }

    public string PolicyOwner { get; set; }

    public string PolicyOwnerSortName { get; set; }

    public string PolicyOwnerEmail { get; set; }

    public string CoverageBeneficiaryLong { get; set; }

    public string CoverageBeneficiaryNamed { get; set; }

    public string PolicyCompany { get; set; }

    public string PolicyCompanyAbbr { get; set; }

    public string PolicyNumber { get; set; }

    public string CertificateId { get; set; }

    public string CoverageClass { get; set; }

    public string CoveragePlan { get; set; }

    public string CoverageType { get; set; }

    public decimal CoverageBenefit { get; set; }

    public string CoverageBenefitMode { get; set; }

    public string PrimaryCoverageYn { get; set; }

    public string QualifiedPlanType { get; set; }

    public int CoverageParticipants { get; set; }

    public string PremiumModeAbbr { get; set; }

    public decimal? PremiumPolicyModalTotal { get; set; }

    public decimal? PremiumPolicyAnnualTotal { get; set; }

    public int? UniquePolicyInsuredNameId { get; set; }

    public int UniqueCoverageInsuredNameId { get; set; }

    public string CoveragePrimaryInsured { get; set; }

    public string CoveragePrimaryInsuredSortName { get; set; }

    public string CoverageStatus { get; set; }

    public string CoverageApprovalBasis { get; set; }

    public string RenewalProvision { get; set; }

    public DateTime? CoverageSubmitDate { get; set; }

    public string CoverageSubmitMonthYear { get; set; }

    public DateTime? PolicyIssueDate { get; set; }

    public string PolicyIssueMonthYear { get; set; }

    public DateTime? CoverageEffectiveDate { get; set; }

    public string CoverageEffectiveMonthYear { get; set; }

    public string CoverageEffectiveMonthDay { get; set; }

    public DateTime? CoverageCompletedDate { get; set; }

    public string CoverageCompletedMonthYear { get; set; }

    public DateTime? CoverageExpirationDate { get; set; }

    public string CoverageExpirationMonthYear { get; set; }

    public DateTime? CoverageTerminationDate { get; set; }

    public string CoverageTerminationMonthYear { get; set; }

    public DateTime? CoverageConversionDate { get; set; }

    public string ConversionMonthYear { get; set; }

    public DateTime? CoverageRenewalDate { get; set; }

    public string CoverageRenewalMonthYear { get; set; }

    public double? CoverageYear { get; set; }

    public decimal PremiumCoverageBaseAnnual { get; set; }

    public decimal PremiumCoverageExcessAnnual1 { get; set; }

    public decimal PremiumCoverageExcessAnnual2 { get; set; }

    public decimal PremiumCoverageAnnualTotal { get; set; }

    public decimal? PremiumCoverageModalTotal { get; set; }

    public string CoverageDividendOption { get; set; }

    public string FundingOption { get; set; }

    public decimal CoverageCashValue { get; set; }

    public decimal CoverageOtherValue { get; set; }

    public decimal? PolicyLoanAmount { get; set; }

    public decimal? PolicySurrenderCharge { get; set; }

    public decimal? PolicySurrenderValue { get; set; }

    public decimal? PolicyNetCashValue { get; set; }

    public decimal? PolicyNetBenefit { get; set; }

    public decimal? PolicyPremiumToDate { get; set; }

    public DateTime? PremiumLastPaidDate { get; set; }

    public DateTime? PremiumsPaidThruDate { get; set; }

    public DateTime? PremiumNextDueDate { get; set; }

    public string CoverageUnderwriter { get; set; }

    public decimal CoverageTotalRiderCashValue { get; set; }

    public decimal CoverageTotalRiderLoanAmount { get; set; }

    public decimal CommissionCoverage1stYrTotal { get; set; }

    public decimal? CommissionPolicy1stYrTotal { get; set; }

    public string GroupMasterCoverage { get; set; }

    public int GroupMasterCoverageUniqueId { get; set; }
}