// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportFileHistoryAccount
{
    public string ClientName { get; set; }

    public string Holding { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public string Description { get; set; }

    public int? CategoryId { get; set; }

    public string Category { get; set; }

    public int ActionId { get; set; }

    public string Action { get; set; }

    public DateTime? ActionDate { get; set; }

    public string UserName { get; set; }

    public DateTime? FileDate { get; set; }

    public Guid UniqueFileId { get; set; }

    public string FileSource { get; set; }

    public int? ContactId { get; set; }

    public int ReferenceId { get; set; }

    public string Reference { get; set; }

    public int FileHistoryLogKeyId { get; set; }

    public int DetailKeyId { get; set; }
}