// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportHouseholdMember
{
    public int UniqueMemberNameId { get; set; }

    public int UniqueMemberId { get; set; }

    public int UniqueHouseholdHeadNameId { get; set; }

    public int UniqueHouseholdId { get; set; }

    public string HouseholdName { get; set; }

    public string MemberFullname { get; set; }

    public string MemberSortName { get; set; }

    public string MemberNameTypeDescriptionPrimary { get; set; }

    public string MemberRelationToHead { get; set; }

    public DateTime? MemberDateOfBirth { get; set; }

    public int? MemberAgeActual { get; set; }

    public string HeadFullname { get; set; }

    public string HeadNameTypeDescriptionPrimary { get; set; }

    public DateTime? HeadDateOfBirth { get; set; }

    public int? HeadAgeActual { get; set; }

    public string MemberPrimaryProducer { get; set; }
}