// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportCommTransaction
{
    public int UniquePolicyId { get; set; }

    public int UniqueCoverageId { get; set; }

    public int UniqueTransactionId { get; set; }

    public int UniqueRateTableSetId { get; set; }

    public int UniqueCompanyId { get; set; }

    public int UniqueCoverageTypeId { get; set; }

    public int UniqueAgencyId { get; set; }

    public int PolicyProducer1UniqueId { get; set; }

    public string PolicyProducer1 { get; set; }

    public int PolicyProducer2UniqueId { get; set; }

    public int PolicyProducer3UniqueId { get; set; }

    public int PolicyProducer4UniqueId { get; set; }

    public int PolicyManager1UniqueId { get; set; }

    public int PolicyManager2UniqueId { get; set; }

    public int PolicyManager3UniqueId { get; set; }

    public int PolicyManager4UniqueId { get; set; }

    public string PolicyNumber { get; set; }

    public string CoveragePlan { get; set; }

    public string PolicyCompanyAbbr { get; set; }

    public string NormalTrailer { get; set; }

    public int Status { get; set; }

    public DateTime? TransDueDate { get; set; }

    public string TransComment { get; set; }

    public int CoverageYear { get; set; }

    public string FirstRenewal { get; set; }

    public string AgencyName { get; set; }

    public decimal? AgencyGrossDue { get; set; }

    public decimal AgencyGrossPaid { get; set; }

    public decimal? AgencyDistributionsDue { get; set; }

    public decimal AgencyDistributionsPaid { get; set; }

    public decimal? AgencyNetDue { get; set; }

    public decimal AgencyNetPaid { get; set; }

    public decimal? ProducersGrossDue { get; set; }

    public decimal ProducersGrossPaid { get; set; }

    public decimal? ProducersDirectDue { get; set; }

    public decimal ProducersDirectPaid { get; set; }

    public decimal? ManagersGrossDue { get; set; }

    public decimal ManagersGrossPaid { get; set; }

    public decimal? ManagersDirectDue { get; set; }

    public decimal ManagersDirectPaid { get; set; }

    public decimal? TotalDirectDue { get; set; }

    public decimal? TotalDirectPaid { get; set; }

    public DateTime? PaidDateMin { get; set; }

    public DateTime? PaidDateMax { get; set; }

    public string RateTableSetName { get; set; }

    public string PolicyOwnerSortName { get; set; }

    public int PolicyOwnerUniqueId { get; set; }

    public string CoveragePrimaryInsuredSortName { get; set; }

    public int CoveragePrimaryInsuredUniqueId { get; set; }
}