// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportInvestmentMgmt
{
    public int UniqueNameId { get; set; }

    public int UniqueInvestorId { get; set; }

    public int UniqueAccountId { get; set; }

    public int UniqueInvestmentId { get; set; }

    public int? UniqueCustodianId { get; set; }

    public string AccountProducer1 { get; set; }

    public string AccountProducer2 { get; set; }

    public string AccountManager1 { get; set; }

    public string InvestorFullName { get; set; }

    public string InvestorSortName { get; set; }

    public string InvestorPrimaryProducer { get; set; }

    public int? InvestorPrimaryProducerNameId { get; set; }

    public string InvestorHouseholdName { get; set; }

    public int InvestorHouseholdId { get; set; }

    public decimal? InvestorMarketValue { get; set; }

    public decimal? InvestorHouseholdMarketValue { get; set; }

    public decimal? InvestorGroupWithMarketValue { get; set; }

    public int InvestorHouseholdHeadOfHouseholdUniqueNameId { get; set; }

    public string InvestorHouseholdHeadOfHouseholdFullName { get; set; }

    public string InvestorHouseholdHeadOfHouseholdSortName { get; set; }

    public string AccountNumber { get; set; }

    public string BeneficiaryFreeForm { get; set; }

    public DateTime? AccountClosedDate { get; set; }

    public decimal AccountMarketValue { get; set; }

    public string AccountCustodian { get; set; }

    public string AccountCustodianAbbr { get; set; }

    public string AssetDownloadSource { get; set; }

    public string AccountType { get; set; }

    public string AssetCompany { get; set; }

    public string AssetCompanyAbbr { get; set; }

    public string AssetName { get; set; }

    public string AssetSymbol { get; set; }

    public string AssetCusip { get; set; }

    public string AssetType { get; set; }

    public string AssetCategory { get; set; }

    public DateTime? AssetAcquiredDate { get; set; }

    public DateTime? AssetLiquidatedDate { get; set; }

    public decimal AssetMarketValue { get; set; }

    public DateTime? AssetSharePriceDate { get; set; }

    public decimal AssetShares { get; set; }

    public decimal AssetSharePrice { get; set; }
}