// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportEmail
{
    public int UniqueEmailId { get; set; }

    public int UniqueNameId { get; set; }

    public string Contact { get; set; }

    public string Title { get; set; }

    public string BusinessName { get; set; }

    public string EmailAddress { get; set; }

    public bool IsPrimary { get; set; }

    public string Comment { get; set; }
}