// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportAddress
{
    public int UniqueAddressId { get; set; }

    public int UniqueNameId { get; set; }

    public int UniqueHouseholdId { get; set; }

    public string AddressType { get; set; }

    public string Greeting { get; set; }

    public string Addressee { get; set; }

    public string Title { get; set; }

    public string BusinessName { get; set; }

    public string Street1 { get; set; }

    public string Street2 { get; set; }

    public string Street3 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string ZipCode { get; set; }

    public string CityStateZip { get; set; }

    public string County { get; set; }

    public string Country { get; set; }

    public string Route { get; set; }

    public string AddressPoint { get; set; }

    public bool IsPrimary { get; set; }

    public string Comment { get; set; }
}