// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportAnnuity
{
    public int Pk { get; set; }

    public string ContractNumber { get; set; }

    public string OwnerName { get; set; }

    public string AnnuitantName { get; set; }

    public string AnnuityType { get; set; }

    public string PlanDescription { get; set; }

    public string CompanyDescription { get; set; }

    public DateTime InceptionDate { get; set; }

    public DateTime AnnuitizationDate { get; set; }

    public DateTime IncomeDate { get; set; }

    public decimal? NetCashValue { get; set; }

    public DateTime TotalNetValuesAsOf { get; set; }

    public string StatusDescription { get; set; }

    public string AnnuitySurrenderPeriodDescription { get; set; }

    public DateTime ProjectedSurrenderPeriodEndDate { get; set; }

    public string SurrenderPeriodRemaining { get; set; }

    public int CoverageKeyId { get; set; }

    public int BaseCoverageKeyId { get; set; }

    public int PolicyKeyId { get; set; }

    public int PlanKeyId { get; set; }

    public int AccountKeyId { get; set; }

    public int ParticipatingPolicies { get; set; }

    public int UniqueNameId { get; set; }

    public decimal? InterestRate { get; set; }
}