// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportDownloadRegistration
{
    public int UniqueRegistrationId { get; set; }

    public int UniqueAccountId { get; set; }

    public int UniquePolicyId { get; set; }

    public DateTime? RegistrationDate { get; set; }

    public string RegistrationNumber { get; set; }

    public string RegistrationBlock { get; set; }

    public string ModuleShortName { get; set; }

    public string ModuleLongName { get; set; }
}