// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportFlexFieldWorkflowValue
{
    public int UniqueWorkflowFlexFieldId { get; set; }

    public int UniqueWorkflowId { get; set; }

    public decimal WorkflowFlexField01Numeric { get; set; }

    public decimal WorkflowFlexField02Numeric { get; set; }

    public decimal WorkflowFlexField03Numeric { get; set; }

    public decimal WorkflowFlexField04Numeric { get; set; }

    public decimal WorkflowFlexField05Numeric { get; set; }

    public decimal WorkflowFlexField06Numeric { get; set; }

    public int WorkflowFlexField07Numeric { get; set; }

    public int WorkflowFlexField08Numeric { get; set; }

    public string WorkflowFlexField09Text { get; set; }

    public string WorkflowFlexField10Text { get; set; }

    public string WorkflowFlexField11Text { get; set; }

    public string WorkflowFlexField12Text { get; set; }

    public DateTime? WorkflowFlexField13Date { get; set; }

    public DateTime? WorkflowFlexField14Date { get; set; }

    public DateTime? WorkflowFlexField15Date { get; set; }

    public DateTime? WorkflowFlexField16Date { get; set; }

    public string WorkflowFlexField17Text { get; set; }

    public string WorkflowFlexField18Text { get; set; }

    public string WorkflowFlexField19Text { get; set; }

    public string WorkflowFlexField20Text { get; set; }

    public DateTime? WorkflowFlexField21Date { get; set; }

    public DateTime? WorkflowFlexField22Date { get; set; }

    public string WorkflowFlexField23Text { get; set; }

    public string WorkflowFlexField24Text { get; set; }

    public string WorkflowFlexField25Text { get; set; }

    public string WorkflowFlexField26Text { get; set; }

    public string WorkflowFlexField27Text { get; set; }

    public string WorkflowFlexField28Text { get; set; }

    public string WorkflowFlexField29Text { get; set; }

    public string WorkflowFlexField30Text { get; set; }
}