// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportPhone
{
    public int UniquePhoneId { get; set; }

    public int UniqueNameId { get; set; }

    public int UniqueHoldholdId { get; set; }

    public string PhoneType { get; set; }

    public string Contact { get; set; }

    public string CountryCode { get; set; }

    public string Areacode { get; set; }

    public string PhoneNumber { get; set; }

    public string PhoneExtension { get; set; }

    public string FullPhone { get; set; }

    public bool? IsPrimary { get; set; }

    public string Comment { get; set; }
}