// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportInsuranceNote
{
    public int UniqueNoteId { get; set; }

    public int UniquePolicyId { get; set; }

    public int UniquePolicyOwnerId { get; set; }

    public int UniquePolicyPrimaryInsuredId { get; set; }

    public string Topic { get; set; }

    public string NoteContent { get; set; }

    public string WhoChanged { get; set; }

    public DateTime? LastChanged { get; set; }

    public string WhoAdded { get; set; }

    public DateTime? WhenAdded { get; set; }

    public DateTime? NoteFollowUpDate { get; set; }

    public bool? NoteFollowUpCompletedYn { get; set; }

    public int UniquePrivateNoteUserId { get; set; }

    public string PrivateNoteUserName { get; set; }
}