// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportFlexFieldLabel
{
    public int UniqueLabelId { get; set; }

    public int UniqueCodeId { get; set; }

    public string FieldLabel01 { get; set; }

    public string FieldLabel02 { get; set; }

    public string FieldLabel03 { get; set; }

    public string FieldLabel04 { get; set; }

    public string FieldLabel05 { get; set; }

    public string FieldLabel06 { get; set; }

    public string FieldLabel07 { get; set; }

    public string FieldLabel08 { get; set; }

    public string FieldLabel09 { get; set; }

    public string FieldLabel10 { get; set; }

    public string FieldLabel11 { get; set; }

    public string FieldLabel12 { get; set; }

    public string FieldLabel13 { get; set; }

    public string FieldLabel14 { get; set; }

    public string FieldLabel15 { get; set; }

    public string FieldLabel16 { get; set; }

    public string FieldLabel17 { get; set; }

    public string FieldLabel18 { get; set; }

    public string FieldLabel19 { get; set; }

    public string FieldLabel20 { get; set; }

    public string FieldLabel21 { get; set; }

    public string FieldLabel22 { get; set; }

    public string FieldLabel23 { get; set; }

    public string FieldLabel24 { get; set; }

    public string FieldLabel25 { get; set; }

    public string FieldLabel26 { get; set; }

    public string FieldLabel27 { get; set; }

    public string FieldLabel28 { get; set; }

    public string FieldLabel29 { get; set; }

    public string FieldLabel30 { get; set; }
}