// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportMarket
{
    public int UniqueNameId { get; set; }

    public string MarketDescription { get; set; }

    public DateTime? LastChange { get; set; }

    public string WhoChange { get; set; }

    public DateTime? FollowupDate { get; set; }
}