// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwReportPolicyNewBiz
{
    public int UniqueNewBizId { get; set; }

    public int UniqueNameId { get; set; }

    public int UniqueNewBizNameId { get; set; }

    public int UniqueCoverageId { get; set; }

    public string OwnerFullName { get; set; }

    public string OwnerFirstName { get; set; }

    public string OwnerLastName { get; set; }

    public string OwnerMiddleName { get; set; }

    public string OwnerSortName { get; set; }

    public int UniqueInsuredNameId { get; set; }

    public string InsuredFullName { get; set; }

    public string InsuredFirstName { get; set; }

    public string InsuredLastName { get; set; }

    public string InsuredMiddleName { get; set; }

    public string InsuredSortName { get; set; }

    public string ActionComment { get; set; }

    public string ActionPriority { get; set; }

    public DateTime? ActionInitiatedDate { get; set; }

    public DateTime? ActionCompletedDate { get; set; }

    public bool? ActionCompletedYn { get; set; }

    public string VendorFullName { get; set; }

    public DateTime? ActionFollowupDate { get; set; }

    public string PolicyNumber { get; set; }

    public decimal PremiumPolicyAnnualTotal { get; set; }

    public string Action { get; set; }

    public string ActionCodeAbbr { get; set; }

    public string ActionCodeDescription { get; set; }

    public string ActionLastChangedBy { get; set; }

    public string ActionInitiatedBy { get; set; }

    public string PolicyCompany { get; set; }

    public string CoverageClass { get; set; }

    public string CoveragePlan { get; set; }

    public decimal PremiumCoverageAnnualTotal { get; set; }

    public decimal CoverageBenefit { get; set; }

    public DateTime? CoverageSubmitDate { get; set; }

    public DateTime? CoverageEffectiveDate { get; set; }

    public string CoverageStatus { get; set; }

    public string PolicyProducer1 { get; set; }

    public decimal? CommissionCoverage1stYrTotal { get; set; }

    public decimal AnnualPremium { get; set; }
}