// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rhyous.DataMigration.AdvisorsAssistant.Models;

public partial class VwViewscreenReportClientInsurance
{
    public Guid RelationGuid { get; set; }

    public string PrimaryInsured { get; set; }

    public string Owner { get; set; }

    public string Producer1 { get; set; }

    public int UniqueNameId { get; set; }

    public int UniquePolicyId { get; set; }

    public int UniqueCoverageId { get; set; }

    public int IKeyBaseCoverage { get; set; }

    public int PrimaryInsuredUniqueNameId { get; set; }

    public int OwnerUniqueNameId { get; set; }

    public int RelationshipCodeKeyId { get; set; }

    public int HeadOfHouseholdUniqueNameId { get; set; }

    public int UniqueStatusCodeId { get; set; }

    public int UniqueAnnuitySurrenderPeriodCodeId { get; set; }

    public string PolicyNumber { get; set; }

    public string CoverageType { get; set; }

    public string CoveragePlan { get; set; }

    public string Company { get; set; }

    public DateTime? CoverageEffectiveDate { get; set; }

    public DateTime? DTermination { get; set; }

    public string StatusCoverage { get; set; }

    public string PremiumMode { get; set; }

    public decimal TotalBenefit { get; set; }

    public decimal TotalPremium { get; set; }

    public decimal TotalModalPremium { get; set; }

    public int Producer1UniqueId { get; set; }

    public int Producer1UniqueNameId { get; set; }

    public int Producer2UniqueId { get; set; }

    public int Producer2UniqueNameId { get; set; }

    public int Producer3UniqueId { get; set; }

    public int Producer3UniqueNameId { get; set; }

    public int Producer4UniqueId { get; set; }

    public int Producer4UniqueNameId { get; set; }

    public int Producer5UniqueId { get; set; }

    public int Producer5UniqueNameId { get; set; }

    public int Producer6UniqueId { get; set; }

    public int Producer6UniqueNameId { get; set; }

    public int Producer7UniqueId { get; set; }

    public int Producer7UniqueNameId { get; set; }

    public int Producer8UniqueId { get; set; }

    public int Producer8UniqueNameId { get; set; }

    public int PerspectiveKeyId { get; set; }

    public int ProductClassCodeKeyId { get; set; }
}